// Template Registry — Central catalog of all available templates
// Each template entry references a .liquid file in /app/templates/

export const TEMPLATE_CATEGORIES = {
    sections: {
        label: 'Sections',
        description: 'Modular blocks you can add to any page',
    },
    pages: {
        label: 'Full Pages',
        description: 'Complete page layouts ready to publish',
    },
};

export const TEMPLATE_NICHES = [
    { id: 'skincare', label: 'Skincare & Beauty', emoji: '🧴' },
    { id: 'fashion', label: 'Fashion & Apparel', emoji: '👗' },
    { id: 'food', label: 'Food & Beverage', emoji: '🍕' },
    { id: 'electronics', label: 'Tech & Electronics', emoji: '💻' },
    { id: 'fitness', label: 'Fitness & Sports', emoji: '🏋️' },
    { id: 'home', label: 'Home & Decor', emoji: '🏠' },
    { id: 'pets', label: 'Pets', emoji: '🐾' },
    { id: 'jewelry', label: 'Jewelry & Accessories', emoji: '💎' },
    { id: 'kids', label: 'Kids & Baby', emoji: '👶' },
    { id: 'wellness', label: 'Health & Wellness', emoji: '🌿' },
];

export const TEMPLATE_STYLES = [
    { id: 'minimal', label: 'Ultra-Minimal', color: '#6b7280' },
    { id: 'glassmorphism', label: 'Glassmorphism', color: '#a78bfa' },
    { id: 'editorial', label: 'Editorial / Classy', color: '#92400e' },
    { id: 'creative', label: 'Creative / Graphic', color: '#ec4899' },
    { id: 'brutalist', label: 'Brutalist', color: '#111827' },
    { id: 'darkmode', label: 'Dark / Neon', color: '#10b981' },
];

export const SECTION_TYPES = [
    { id: 'hero', label: 'Hero Banner', icon: '🖼️' },
    { id: 'features', label: 'Feature Grid', icon: '📊' },
    { id: 'cta', label: 'Call to Action', icon: '🎯' },
    { id: 'testimonials', label: 'Testimonials', icon: '⭐' },
    { id: 'faq', label: 'FAQ Accordion', icon: '❓' },
    { id: 'gallery', label: 'Image Gallery', icon: '🖼️' },
    { id: 'product-grid', label: 'Product Cards', icon: '🛍️' },
    { id: 'newsletter', label: 'Newsletter Signup', icon: '📧' },
    { id: 'stats', label: 'Stats / Numbers', icon: '📈' },
    { id: 'trust', label: 'Trust Badges', icon: '🛡️' },
    { id: 'video', label: 'Video Section', icon: '🎬' },
    { id: 'marquee', label: 'Marquee Ticker', icon: '📢' },
    { id: 'pricing', label: 'Pricing Table', icon: '💰' },
    { id: 'team', label: 'Team / About', icon: '👥' },
    { id: 'countdown', label: 'Countdown Timer', icon: '⏱️' },
    { id: 'categories', label: 'Category Grid', icon: '🗂️' },
    { id: 'blog', label: 'Blog Posts', icon: '📝' },
    { id: 'banner', label: 'Promo Banner', icon: '🎪' },
    { id: 'comparison', label: 'Before & After', icon: '🔄' },
    { id: 'footer', label: 'Footer', icon: '🔻' },
];

// ═══ TEMPLATE ENTRIES ═══
// Each entry has: id, name, category, sectionType, niche, style, 
// description, previewColors, liquidFile, usageCount
export const TEMPLATES = [
    {
        id: 'hero-glas-skincare-01',
        name: 'Radiance — Glass Hero',
        category: 'sections',
        sectionType: 'hero',
        niche: 'skincare',
        style: 'glassmorphism',
        description: 'Split-screen asymmetrical hero with video background, floating glass stat chips, gradient CTA, and sticky add-to-cart bar. Built for premium skincare brands.',
        previewColors: ['#0a0a0f', '#a78bfa', '#6d5bff', '#f0f0f5'],
        liquidFile: 'sections/hero-glassmorphism-skincare.liquid',
        usageCount: 3291,
        isPremium: false,
        tags: ['hero', 'video', 'glassmorphism', 'sticky-atc', 'skincare', 'premium'],
    },
    {
        id: 'hero-minimal-fashion-01',
        name: 'Monochrome — Clean Hero',
        category: 'sections',
        sectionType: 'hero',
        niche: 'fashion',
        style: 'minimal',
        description: 'Swiss-inspired minimal hero with heavy white space, monochrome palette, and bold sans-serif typography. Perfect for high-end fashion labels.',
        previewColors: ['#ffffff', '#111827', '#e5e7eb', '#6b7280'],
        liquidFile: 'sections/hero-minimal-fashion.liquid',
        usageCount: 2104,
        isPremium: false,
        tags: ['hero', 'minimal', 'fashion', 'typography', 'clean'],
    },
    {
        id: 'hero-editorial-jewelry-01',
        name: 'Luxe — Editorial Hero',
        category: 'sections',
        sectionType: 'hero',
        niche: 'jewelry',
        style: 'editorial',
        description: 'Magazine-editorial hero with serif headings, elegant gold accents, and a full-width product shot. For luxury jewelry and accessories.',
        previewColors: ['#faf7f2', '#1a1a1a', '#c9a961', '#8b7355'],
        liquidFile: 'sections/hero-editorial-jewelry.liquid',
        usageCount: 1847,
        isPremium: false,
        tags: ['hero', 'editorial', 'luxury', 'jewelry', 'serif'],
    },
    {
        id: 'hero-creative-streetwear-01',
        name: 'GRAFFITI — Bold Hero',
        category: 'sections',
        sectionType: 'hero',
        niche: 'fashion',
        style: 'creative',
        description: 'High-energy creative hero with overlapping elements, bold neon typography, and custom SVG shapes. Built for streetwear drops.',
        previewColors: ['#0d0d0d', '#ff3366', '#00ff88', '#ffd60a'],
        liquidFile: 'sections/hero-creative-streetwear.liquid',
        usageCount: 2567,
        isPremium: false,
        tags: ['hero', 'creative', 'bold', 'streetwear', 'neon'],
    },
    {
        id: 'hero-darkmode-electronics-01',
        name: 'Neon Grid — Tech Hero',
        category: 'sections',
        sectionType: 'hero',
        niche: 'electronics',
        style: 'darkmode',
        description: 'Cyberpunk-inspired hero with neon grid lines, glowing accents, and a floating product render. For tech and electronics brands.',
        previewColors: ['#0a0a12', '#00ff88', '#635bff', '#e0e0e0'],
        liquidFile: 'sections/hero-darkmode-electronics.liquid',
        usageCount: 1956,
        isPremium: false,
        tags: ['hero', 'dark', 'neon', 'tech', 'electronics', 'cyberpunk'],
    },
    // ── Feature Grids ──
    {
        id: 'features-glass-skincare-01',
        name: 'Crystal Grid — 3-Column Features',
        category: 'sections',
        sectionType: 'features',
        niche: 'skincare',
        style: 'glassmorphism',
        description: 'Glassmorphism feature cards in a 3-column grid with icon badges, hover lift effects, and gradient text highlights.',
        previewColors: ['#0a0a0f', '#a78bfa', '#1a1a2e', '#f0f0f5'],
        liquidFile: 'sections/features-glass-skincare.liquid',
        usageCount: 4703,
        isPremium: false,
        tags: ['features', 'grid', 'glassmorphism', 'cards', 'skincare'],
    },
    {
        id: 'features-minimal-wellness-01',
        name: 'Zen Grid — Minimal Features',
        category: 'sections',
        sectionType: 'features',
        niche: 'wellness',
        style: 'minimal',
        description: 'Ultra-clean feature grid with generous white space, thin borders, and subtle icon animations. Perfect for wellness brands.',
        previewColors: ['#ffffff', '#10b981', '#f8f9fb', '#374151'],
        liquidFile: 'sections/features-minimal-wellness.liquid',
        usageCount: 3890,
        isPremium: false,
        tags: ['features', 'minimal', 'clean', 'wellness', 'health'],
    },
    // ── Testimonials ──
    {
        id: 'testimonials-glass-01',
        name: 'Trust Wave — Glass Testimonials',
        category: 'sections',
        sectionType: 'testimonials',
        niche: 'skincare',
        style: 'glassmorphism',
        description: 'Auto-scrolling testimonial cards with glassmorphism styling, star ratings, verified badges, and before/after thumbnails.',
        previewColors: ['#0a0a0f', '#a78bfa', '#fbbf24', '#f0f0f5'],
        liquidFile: 'sections/testimonials-glass.liquid',
        usageCount: 5039,
        isPremium: false,
        tags: ['testimonials', 'reviews', 'social-proof', 'glass', 'stars'],
    },
    {
        id: 'testimonials-editorial-01',
        name: 'Vogue Quotes — Editorial Testimonials',
        category: 'sections',
        sectionType: 'testimonials',
        niche: 'jewelry',
        style: 'editorial',
        description: 'Magazine-style testimonials with large serif quotes, customer photos in circular frames, and elegant dividers.',
        previewColors: ['#faf7f2', '#1a1a1a', '#c9a961', '#6b7280'],
        liquidFile: 'sections/testimonials-editorial.liquid',
        usageCount: 2901,
        isPremium: false,
        tags: ['testimonials', 'editorial', 'quotes', 'luxury', 'serif'],
    },
    // ── CTA Sections ──
    {
        id: 'cta-gradient-01',
        name: 'Pulse — Gradient CTA',
        category: 'sections',
        sectionType: 'cta',
        niche: 'fitness',
        style: 'creative',
        description: 'High-impact CTA section with bold gradient background, pulsing accent ring, countdown urgency, and dual buttons.',
        previewColors: ['#1e1b4b', '#6366f1', '#ec4899', '#fbbf24'],
        liquidFile: 'sections/cta-gradient-fitness.liquid',
        usageCount: 6120,
        isPremium: false,
        tags: ['cta', 'gradient', 'bold', 'urgency', 'fitness'],
    },
    {
        id: 'cta-minimal-01',
        name: 'Whisper — Minimal CTA',
        category: 'sections',
        sectionType: 'cta',
        niche: 'home',
        style: 'minimal',
        description: 'Quiet, refined CTA with a single headline, subtle underline animation, and one clean button. Less is more.',
        previewColors: ['#fafafa', '#111827', '#6b7280', '#000000'],
        liquidFile: 'sections/cta-minimal-home.liquid',
        usageCount: 3780,
        isPremium: false,
        tags: ['cta', 'minimal', 'simple', 'home-decor', 'clean'],
    },
    // ── FAQ ──
    {
        id: 'faq-glass-01',
        name: 'Help Desk — Glass FAQ',
        category: 'sections',
        sectionType: 'faq',
        niche: 'skincare',
        style: 'glassmorphism',
        description: 'Interactive accordion FAQ with glassmorphism cards, smooth expand animations, and search bar. Reduces support tickets.',
        previewColors: ['#0a0a0f', '#a78bfa', '#1a1a2e', '#f0f0f5'],
        liquidFile: 'sections/faq-glass.liquid',
        usageCount: 4250,
        isPremium: false,
        tags: ['faq', 'accordion', 'glass', 'interactive', 'support'],
    },
    // ── Newsletter ──
    {
        id: 'newsletter-dark-01',
        name: 'Subscribe — Dark Newsletter',
        category: 'sections',
        sectionType: 'newsletter',
        niche: 'fashion',
        style: 'darkmode',
        description: 'Dark mode newsletter section with gradient input border animation, inline submit, and social proof counter.',
        previewColors: ['#0d0d0d', '#635bff', '#00ff88', '#f0f0f5'],
        liquidFile: 'sections/newsletter-dark.liquid',
        usageCount: 3456,
        isPremium: false,
        tags: ['newsletter', 'email', 'dark', 'signup', 'gradient'],
    },
    // ── Stats ──
    {
        id: 'stats-counter-01',
        name: 'Impact — Animated Stats',
        category: 'sections',
        sectionType: 'stats',
        niche: 'wellness',
        style: 'minimal',
        description: 'Animated number counters that count up on scroll, with subtle gradient backgrounds and clean typography.',
        previewColors: ['#ffffff', '#111827', '#10b981', '#6b7280'],
        liquidFile: 'sections/stats-counter.liquid',
        usageCount: 4100,
        isPremium: false,
        tags: ['stats', 'numbers', 'counter', 'animation', 'scroll'],
    },
    // ── Trust Badges ──
    {
        id: 'trust-logos-01',
        name: 'As Seen In — Logo Bar',
        category: 'sections',
        sectionType: 'trust',
        niche: 'skincare',
        style: 'minimal',
        description: 'Scrolling logo marquee with "As Seen In" press logos, payment badges, and certification icons.',
        previewColors: ['#ffffff', '#6b7280', '#e5e7eb', '#111827'],
        liquidFile: 'sections/trust-logos.liquid',
        usageCount: 7200,
        isPremium: false,
        tags: ['trust', 'logos', 'press', 'social-proof', 'marquee'],
    },
    // ── Marquee ──
    {
        id: 'marquee-brutalist-01',
        name: 'SHOUT — Brutalist Marquee',
        category: 'sections',
        sectionType: 'marquee',
        niche: 'fashion',
        style: 'brutalist',
        description: 'Bold, oversized scrolling text marquee with raw edges and high contrast. Grabs immediate attention.',
        previewColors: ['#ffffff', '#000000', '#ff0000', '#ffff00'],
        liquidFile: 'sections/marquee-brutalist.liquid',
        usageCount: 2300,
        isPremium: false,
        tags: ['marquee', 'brutalist', 'bold', 'scroll', 'attention'],
    },
    // ── Product Grid ──
    {
        id: 'products-glass-01',
        name: 'Showcase — Glass Product Cards',
        category: 'sections',
        sectionType: 'product-grid',
        niche: 'electronics',
        style: 'glassmorphism',
        description: 'Glassmorphism product cards with hover image swap, quick-view overlay, and animated add-to-cart.',
        previewColors: ['#0a0a0f', '#635bff', '#a78bfa', '#f0f0f5'],
        liquidFile: 'sections/products-glass.liquid',
        usageCount: 5100,
        isPremium: false,
        tags: ['products', 'grid', 'glass', 'cards', 'shop'],
    },
    // ── Video Section ──
    {
        id: 'video-cinematic-01',
        name: 'Cinema — Video Showcase',
        category: 'sections',
        sectionType: 'video',
        niche: 'food',
        style: 'editorial',
        description: 'Cinematic video section with play button overlay, custom poster frame, and elegant caption typography.',
        previewColors: ['#1a1a1a', '#ffffff', '#c9a961', '#6b7280'],
        liquidFile: 'sections/video-cinematic.liquid',
        usageCount: 2800,
        isPremium: false,
        tags: ['video', 'cinematic', 'play', 'editorial', 'fullwidth'],
    },
    // ── Gallery ──
    {
        id: 'gallery-masonry-01',
        name: 'Mosaic — Masonry Gallery',
        category: 'sections',
        sectionType: 'gallery',
        niche: 'home',
        style: 'minimal',
        description: 'Pinterest-style masonry image gallery with lightbox zoom, hover captions, and lazy loading.',
        previewColors: ['#ffffff', '#111827', '#f1f3f5', '#6b7280'],
        liquidFile: 'sections/gallery-masonry.liquid',
        usageCount: 3400,
        isPremium: false,
        tags: ['gallery', 'masonry', 'images', 'lightbox', 'pinterest'],
    },
    // ── Countdown ──
    {
        id: 'countdown-urgency-01',
        name: 'LAST CHANCE — Countdown Banner',
        category: 'sections',
        sectionType: 'countdown',
        niche: 'fashion',
        style: 'creative',
        description: 'Full-width countdown timer with flip animation, gradient background, and urgency copywriting triggers.',
        previewColors: ['#1e1b4b', '#ec4899', '#fbbf24', '#ffffff'],
        liquidFile: 'sections/countdown-urgency.liquid',
        usageCount: 4600,
        isPremium: false,
        tags: ['countdown', 'timer', 'urgency', 'scarcity', 'sale'],
    },
];
