export const SECTION_CATEGORIES = [
    { id: 'cro-home', name: '🎯 CRO Home Sections', description: 'High-converting home page sections (20-40% CR lift)', icon: 'Target' },
    { id: 'cro-product', name: '🛒 CRO Product Sections', description: 'Product page sections for maximum conversions', icon: 'ShoppingCart' },
    { id: 'header', name: 'Header', description: 'Navigation bars and branding', icon: 'Layout' },
    { id: 'marquee', name: 'Marquee / Tickers', description: 'Infinite scrolling announcement bands', icon: 'Type' },
    { id: 'promo', name: 'Promo Posters', description: 'Large format promotional banners', icon: 'Image' },
    { id: 'snack', name: 'Promo Code Snacks', description: 'Compact discount code and offer bars', icon: 'Tag' },
    { id: 'category', name: 'Category Sections', description: 'Collection grids and carousels', icon: 'Grid' },
    { id: 'feature', name: 'Featured Collections', description: 'Product grids and sliders', icon: 'ShoppingBag' },
    { id: 'trust', name: 'Trust Badges', description: 'Guarantees and value props', icon: 'Shield' },
    { id: 'announcement', name: 'Announcement Bars', description: '10 creative announcement styles', icon: 'Megaphone' },
    { id: 'hero', name: 'Hero Sections', description: '10 premium hero banners', icon: 'Image' }
];

// ── Auto-generate expansion entries for niches 02–05 ─────────────────
const NICHE_LABELS = {
    '02': 'Streetwear', '03': 'Tech', '04': 'Health', '05': 'Beauty', '06': 'Auto'
};
const EXPANSION_DEFS = [
    // [keyPrefix, category, nicheFileMap]  — nicheFileMap: { nicheId: filePrefix }
    ['header', 'header', { '02': 'cf-header-02', '03': 'cf-header-03', '04': 'cf-header-04', '05': 'cf-header-05', '06': 'cf-header-06' }],
    ['marquee', 'marquee', { '02': 'cf-marquee-02', '03': 'cf-marquee-03', '04': 'cf-marquee-04', '05': 'cf-marquee-05', '06': 'cf-marquee-06' }],
    ['promo', 'promo', { '02': 'cf-promo-02', '03': 'cf-promo-03', '04': 'cf-promo-04', '05': 'cf-promo-05', '06': 'cf-promo-06' }],
    ['snack', 'snack', { '02': 'cf-promo-snack-02', '03': 'cf-promo-snack-03', '04': 'cf-promo-snack-04', '05': 'cf-promo-snack-05', '06': 'cf-promo-snack-06' }],
    ['cat', 'category', { '02': 'cf-category-02', '03': 'cf-category-grid-03', '04': 'cf-category-04', '05': 'cf-category-05', '06': 'cf-category-grid-06' }],
    ['feat', 'feature', { '02': 'cf-featured-collection-02', '03': 'cf-featured-collection-03', '04': 'cf-featured-collection-04', '05': 'cf-featured-collection-05', '06': 'cf-featured-collection-06' }],
    ['trust', 'trust', { '02': 'cf-trust-badges-02', '03': 'cf-trust-badges-03', '04': 'cf-trust-badges-04', '05': 'cf-trust-badges-05', '06': 'cf-trust-badge-06' }],
];
const COMP_LABELS = { header: 'Header', marquee: 'Marquee', promo: 'Promo', snack: 'Snack', cat: 'Category', feat: 'Featured', trust: 'Trust' };

function buildExpansions() {
    const out = {};
    for (const [compKey, category, nicheMap] of EXPANSION_DEFS) {
        for (const [niche, filePrefix] of Object.entries(nicheMap)) {
            for (let v = 2; v <= 10; v++) {
                const id = `${filePrefix}-v${v}`;
                out[id] = { category, name: `${niche} · ${NICHE_LABELS[niche]} ${COMP_LABELS[compKey]} (v${v})`, file: `${filePrefix}-v${v}.liquid` };
            }
        }
    }
    return out;
}

export const SECTION_FILES = {
    ...buildExpansions(),
    'cf-head-01': { category: 'header', name: '01 · Luxury Header', file: 'cf-head-01.liquid' },
    'cf-head-02': { category: 'header', name: '02 · Streetwear Header', file: 'cf-head-02.liquid' },
    'cf-head-03': { category: 'header', name: '03 · Tech Header', file: 'cf-head-03.liquid' },
    'cf-head-04': { category: 'header', name: '04 · Health Header', file: 'cf-head-04.liquid' },
    'cf-head-05': { category: 'header', name: '05 · Beauty Header', file: 'cf-head-05.liquid' },
    'cf-head-06': { category: 'header', name: '06 · Automotive Header', file: 'cf-head-06.liquid' },
    'cf-head-07': { category: 'header', name: '07 · SaaS Header', file: 'cf-head-07.liquid' },
    'cf-head-08': { category: 'header', name: '08 · Kids Header', file: 'cf-head-08.liquid' },
    'cf-head-09': { category: 'header', name: '09 · Furniture Header', file: 'cf-head-09.liquid' },
    'cf-head-10': { category: 'header', name: '10 · Fitness Header', file: 'cf-head-10.liquid' },
    'cf-head-11': { category: 'header', name: '11 · Men\'s Header', file: 'cf-head-11.liquid' },
    'cf-head-11-v2': { category: 'header', name: '11 · Men\'s Header (v2)', file: 'cf-head-11-v2.liquid' },
    'cf-head-11-v3': { category: 'header', name: '11 · Men\'s Header (v3)', file: 'cf-head-11-v3.liquid' },
    'cf-head-11-v4': { category: 'header', name: '11 · Men\'s Header (v4)', file: 'cf-head-11-v4.liquid' },
    'cf-head-11-v5': { category: 'header', name: '11 · Men\'s Header (v5)', file: 'cf-head-11-v5.liquid' },
    'cf-head-11-v6': { category: 'header', name: '11 · Men\'s Header (v6)', file: 'cf-head-11-v6.liquid' },
    'cf-head-11-v7': { category: 'header', name: '11 · Men\'s Header (v7)', file: 'cf-head-11-v7.liquid' },
    'cf-head-11-v8': { category: 'header', name: '11 · Men\'s Header (v8)', file: 'cf-head-11-v8.liquid' },
    'cf-head-11-v9': { category: 'header', name: '11 · Men\'s Header (v9)', file: 'cf-head-11-v9.liquid' },
    'cf-head-11-v10': { category: 'header', name: '11 · Men\'s Header (v10)', file: 'cf-head-11-v10.liquid' },
    'cf-head-12': { category: 'header', name: '12 · Women\'s Header', file: 'cf-head-12.liquid' },
    'cf-head-13': { category: 'header', name: '13 · Brand Header', file: 'cf-head-13.liquid' },

    'cf-marquee-01': { category: 'marquee', name: '01 · Luxury Marquee', file: 'cf-marquee-01.liquid' },
    'cf-marquee-02': { category: 'marquee', name: '02 · Streetwear Marquee', file: 'cf-marquee-02.liquid' },
    'cf-marquee-03': { category: 'marquee', name: '03 · Tech Marquee', file: 'cf-marquee-03.liquid' },
    'cf-marquee-04': { category: 'marquee', name: '04 · Health Marquee', file: 'cf-marquee-04.liquid' },
    'cf-marquee-05': { category: 'marquee', name: '05 · Beauty Marquee', file: 'cf-marquee-05.liquid' },
    'cf-marquee-06': { category: 'marquee', name: '06 · Auto Marquee', file: 'cf-marquee-06.liquid' },
    'cf-marquee-07': { category: 'marquee', name: '07 · SaaS Marquee', file: 'cf-marquee-07.liquid' },
    'cf-marquee-08': { category: 'marquee', name: '08 · Kids Marquee', file: 'cf-marquee-08.liquid' },
    'cf-marquee-09': { category: 'marquee', name: '09 · Furniture Marquee', file: 'cf-marquee-09.liquid' },
    'cf-marquee-10': { category: 'marquee', name: '10 · Fitness Marquee', file: 'cf-marquee-10.liquid' },
    'cf-marquee-11': { category: 'marquee', name: '11 · Men\'s Marquee', file: 'cf-marquee-11.liquid' },
    'cf-marquee-11-v2': { category: 'marquee', name: '11 · Men\'s Marquee (v2)', file: 'cf-marquee-11-v2.liquid' },
    'cf-marquee-11-v3': { category: 'marquee', name: '11 · Men\'s Marquee (v3)', file: 'cf-marquee-11-v3.liquid' },
    'cf-marquee-11-v4': { category: 'marquee', name: '11 · Men\'s Marquee (v4)', file: 'cf-marquee-11-v4.liquid' },
    'cf-marquee-11-v5': { category: 'marquee', name: '11 · Men\'s Marquee (v5)', file: 'cf-marquee-11-v5.liquid' },
    'cf-marquee-11-v6': { category: 'marquee', name: '11 · Men\'s Marquee (v6)', file: 'cf-marquee-11-v6.liquid' },
    'cf-marquee-11-v7': { category: 'marquee', name: '11 · Men\'s Marquee (v7)', file: 'cf-marquee-11-v7.liquid' },
    'cf-marquee-11-v8': { category: 'marquee', name: '11 · Men\'s Marquee (v8)', file: 'cf-marquee-11-v8.liquid' },
    'cf-marquee-11-v9': { category: 'marquee', name: '11 · Men\'s Marquee (v9)', file: 'cf-marquee-11-v9.liquid' },
    'cf-marquee-11-v10': { category: 'marquee', name: '11 · Men\'s Marquee (v10)', file: 'cf-marquee-11-v10.liquid' },
    'cf-marquee-12': { category: 'marquee', name: '12 · Women\'s Marquee', file: 'cf-marquee-12.liquid' },
    'cf-marquee-13': { category: 'marquee', name: '13 · Brand Marquee', file: 'cf-marquee-13.liquid' },

    'cf-promo-01': { category: 'promo', name: '01 · Luxury Promo', file: 'cf-promo-01.liquid' },
    'cf-promo-02': { category: 'promo', name: '02 · Streetwear Promo', file: 'cf-promo-02.liquid' },
    'cf-promo-03': { category: 'promo', name: '03 · Tech Promo', file: 'cf-promo-03.liquid' },
    'cf-promo-04': { category: 'promo', name: '04 · Health Promo', file: 'cf-promo-04.liquid' },
    'cf-promo-05': { category: 'promo', name: '05 · Beauty Promo', file: 'cf-promo-05.liquid' },
    'cf-promo-06': { category: 'promo', name: '06 · Auto Promo', file: 'cf-promo-06.liquid' },
    'cf-promo-07': { category: 'promo', name: '07 · SaaS Promo', file: 'cf-promo-07.liquid' },
    'cf-promo-08': { category: 'promo', name: '08 · Kids Promo', file: 'cf-promo-08.liquid' },
    'cf-promo-09': { category: 'promo', name: '09 · Furniture Promo', file: 'cf-promo-09.liquid' },
    'cf-promo-10': { category: 'promo', name: '10 · Fitness Promo', file: 'cf-promo-10.liquid' },
    'cf-promo-11': { category: 'promo', name: '11 · Men\'s Promo', file: 'cf-promo-11.liquid' },
    'cf-promo-11-v2': { category: 'promo', name: '11 · Men\'s Promo (v2)', file: 'cf-promo-11-v2.liquid' },
    'cf-promo-11-v3': { category: 'promo', name: '11 · Men\'s Promo (v3)', file: 'cf-promo-11-v3.liquid' },
    'cf-promo-11-v4': { category: 'promo', name: '11 · Men\'s Promo (v4)', file: 'cf-promo-11-v4.liquid' },
    'cf-promo-11-v5': { category: 'promo', name: '11 · Men\'s Promo (v5)', file: 'cf-promo-11-v5.liquid' },
    'cf-promo-11-v6': { category: 'promo', name: '11 · Men\'s Promo (v6)', file: 'cf-promo-11-v6.liquid' },
    'cf-promo-11-v7': { category: 'promo', name: '11 · Men\'s Promo (v7)', file: 'cf-promo-11-v7.liquid' },
    'cf-promo-11-v8': { category: 'promo', name: '11 · Men\'s Promo (v8)', file: 'cf-promo-11-v8.liquid' },
    'cf-promo-11-v9': { category: 'promo', name: '11 · Men\'s Promo (v9)', file: 'cf-promo-11-v9.liquid' },
    'cf-promo-11-v10': { category: 'promo', name: '11 · Men\'s Promo (v10)', file: 'cf-promo-11-v10.liquid' },
    'cf-promo-12': { category: 'promo', name: '12 · Women\'s Promo', file: 'cf-promo-12.liquid' },
    'cf-promo-13': { category: 'promo', name: '13 · Brand Promo', file: 'cf-promo-13.liquid' },

    'cf-snack-01': { category: 'snack', name: '01 · Luxury Snack', file: 'cf-snack-01.liquid' },
    'cf-snack-02': { category: 'snack', name: '02 · Streetwear Snack', file: 'cf-snack-02.liquid' },
    'cf-snack-03': { category: 'snack', name: '03 · Tech Snack', file: 'cf-snack-03.liquid' },
    'cf-snack-04': { category: 'snack', name: '04 · Health Snack', file: 'cf-snack-04.liquid' },
    'cf-snack-05': { category: 'snack', name: '05 · Beauty Snack', file: 'cf-snack-05.liquid' },
    'cf-snack-06': { category: 'snack', name: '06 · Auto Snack', file: 'cf-snack-06.liquid' },
    'cf-snack-07': { category: 'snack', name: '07 · SaaS Snack', file: 'cf-snack-07.liquid' },
    'cf-snack-08': { category: 'snack', name: '08 · Kids Snack', file: 'cf-snack-08.liquid' },
    'cf-snack-09': { category: 'snack', name: '09 · Furniture Snack', file: 'cf-snack-09.liquid' },
    'cf-snack-10': { category: 'snack', name: '10 · Fitness Snack', file: 'cf-snack-10.liquid' },
    'cf-snack-11': { category: 'snack', name: '11 · Men\'s Snack', file: 'cf-snack-11.liquid' },
    'cf-snack-11-v2': { category: 'snack', name: '11 · Men\'s Snack (v2)', file: 'cf-snack-11-v2.liquid' },
    'cf-snack-11-v3': { category: 'snack', name: '11 · Men\'s Snack (v3)', file: 'cf-snack-11-v3.liquid' },
    'cf-snack-11-v4': { category: 'snack', name: '11 · Men\'s Snack (v4)', file: 'cf-snack-11-v4.liquid' },
    'cf-snack-11-v5': { category: 'snack', name: '11 · Men\'s Snack (v5)', file: 'cf-snack-11-v5.liquid' },
    'cf-snack-11-v6': { category: 'snack', name: '11 · Men\'s Snack (v6)', file: 'cf-snack-11-v6.liquid' },
    'cf-snack-11-v7': { category: 'snack', name: '11 · Men\'s Snack (v7)', file: 'cf-snack-11-v7.liquid' },
    'cf-snack-11-v8': { category: 'snack', name: '11 · Men\'s Snack (v8)', file: 'cf-snack-11-v8.liquid' },
    'cf-snack-11-v9': { category: 'snack', name: '11 · Men\'s Snack (v9)', file: 'cf-snack-11-v9.liquid' },
    'cf-snack-11-v10': { category: 'snack', name: '11 · Men\'s Snack (v10)', file: 'cf-snack-11-v10.liquid' },
    'cf-snack-12': { category: 'snack', name: '12 · Women\'s Snack', file: 'cf-snack-12.liquid' },
    'cf-snack-13': { category: 'snack', name: '13 · Brand Snack', file: 'cf-snack-13.liquid' },

    'cf-category-01': { category: 'category', name: '01 · Luxury Categories', file: 'cf-category-01.liquid' },
    'cf-category-02': { category: 'category', name: '02 · Streetwear Categories', file: 'cf-category-02.liquid' },
    'cf-category-03': { category: 'category', name: '03 · Tech Categories', file: 'cf-category-03.liquid' },
    'cf-category-04': { category: 'category', name: '04 · Health Categories', file: 'cf-category-04.liquid' },
    'cf-category-05': { category: 'category', name: '05 · Beauty Categories', file: 'cf-category-05.liquid' },
    'cf-category-06': { category: 'category', name: '06 · Auto Categories', file: 'cf-category-06.liquid' },
    'cf-category-07': { category: 'category', name: '07 · SaaS Categories', file: 'cf-category-07.liquid' },
    'cf-category-08': { category: 'category', name: '08 · Kids Categories', file: 'cf-category-08.liquid' },
    'cf-cat-09': { category: 'category', name: '09 · Furniture Category', file: 'cf-cat-09.liquid' },
    'cf-cat-10': { category: 'category', name: '10 · Fitness Category', file: 'cf-cat-10.liquid' },
    'cf-cat-11': { category: 'category', name: '11 · Men\'s Category', file: 'cf-cat-11.liquid' },
    'cf-cat-11-v2': { category: 'category', name: '11 · Men\'s Category (v2)', file: 'cf-cat-11-v2.liquid' },
    'cf-cat-11-v3': { category: 'category', name: '11 · Men\'s Category (v3)', file: 'cf-cat-11-v3.liquid' },
    'cf-cat-11-v4': { category: 'category', name: '11 · Men\'s Category (v4)', file: 'cf-cat-11-v4.liquid' },
    'cf-cat-11-v5': { category: 'category', name: '11 · Men\'s Category (v5)', file: 'cf-cat-11-v5.liquid' },
    'cf-cat-11-v6': { category: 'category', name: '11 · Men\'s Category (v6)', file: 'cf-cat-11-v6.liquid' },
    'cf-cat-11-v7': { category: 'category', name: '11 · Men\'s Category (v7)', file: 'cf-cat-11-v7.liquid' },
    'cf-cat-11-v8': { category: 'category', name: '11 · Men\'s Category (v8)', file: 'cf-cat-11-v8.liquid' },
    'cf-cat-11-v9': { category: 'category', name: '11 · Men\'s Category (v9)', file: 'cf-cat-11-v9.liquid' },
    'cf-cat-11-v10': { category: 'category', name: '11 · Men\'s Category (v10)', file: 'cf-cat-11-v10.liquid' },
    'cf-cat-12': { category: 'category', name: '12 · Women\'s Category', file: 'cf-cat-12.liquid' },
    'cf-category-13': { category: 'category', name: '13 · Brand Categories', file: 'cf-cat-13.liquid' },

    'cf-feature-01': { category: 'feature', name: '01 · Luxury Lookbook', file: 'cf-feature-01.liquid' },
    'cf-feature-02': { category: 'feature', name: '02 · Streetwear Drop', file: 'cf-feature-02.liquid' },
    'cf-feature-03': { category: 'feature', name: '03 · Tech Showcase', file: 'cf-feature-03.liquid' },
    'cf-feature-04': { category: 'feature', name: '04 · Health Carousel', file: 'cf-feature-04.liquid' },
    'cf-feature-05': { category: 'feature', name: '05 · Beauty Picks', file: 'cf-feature-05.liquid' },
    'cf-feature-06': { category: 'feature', name: '06 · Auto Parts', file: 'cf-feature-06.liquid' },
    'cf-feature-07': { category: 'feature', name: '07 · SaaS Plans', file: 'cf-feature-07.liquid' },
    'cf-feature-08': { category: 'feature', name: '08 · Kids Toys', file: 'cf-feature-08.liquid' },
    'cf-feat-09': { category: 'feature', name: '09 · Furniture Featured', file: 'cf-feat-09.liquid' },
    'cf-feat-10': { category: 'feature', name: '10 · Fitness Featured', file: 'cf-feat-10.liquid' },
    'cf-feat-11': { category: 'feature', name: '11 · Men\'s Featured', file: 'cf-feat-11.liquid' },
    'cf-feat-11-v2': { category: 'feature', name: '11 · Men\'s Featured (v2)', file: 'cf-feat-11-v2.liquid' },
    'cf-feat-11-v3': { category: 'feature', name: '11 · Men\'s Featured (v3)', file: 'cf-feat-11-v3.liquid' },
    'cf-feat-11-v4': { category: 'feature', name: '11 · Men\'s Featured (v4)', file: 'cf-feat-11-v4.liquid' },
    'cf-feat-11-v5': { category: 'feature', name: '11 · Men\'s Featured (v5)', file: 'cf-feat-11-v5.liquid' },
    'cf-feat-11-v6': { category: 'feature', name: '11 · Men\'s Featured (v6)', file: 'cf-feat-11-v6.liquid' },
    'cf-feat-11-v7': { category: 'feature', name: '11 · Men\'s Featured (v7)', file: 'cf-feat-11-v7.liquid' },
    'cf-feat-11-v8': { category: 'feature', name: '11 · Men\'s Featured (v8)', file: 'cf-feat-11-v8.liquid' },
    'cf-feat-11-v9': { category: 'feature', name: '11 · Men\'s Featured (v9)', file: 'cf-feat-11-v9.liquid' },
    'cf-feat-11-v10': { category: 'feature', name: '11 · Men\'s Featured (v10)', file: 'cf-feat-11-v10.liquid' },
    'cf-feat-12': { category: 'feature', name: '12 · Women\'s Featured', file: 'cf-feat-12.liquid' },
    'cf-feature-13': { category: 'feature', name: '13 · Brand Featured', file: 'cf-feature-13.liquid' },

    'cf-trust-01': { category: 'trust', name: '01 · Luxury Trust', file: 'cf-trust-01.liquid' },
    'cf-trust-02': { category: 'trust', name: '02 · Streetwear Trust', file: 'cf-trust-02.liquid' },
    'cf-trust-03': { category: 'trust', name: '03 · Tech Trust', file: 'cf-trust-03.liquid' },
    'cf-trust-04': { category: 'trust', name: '04 · Health Trust', file: 'cf-trust-04.liquid' },
    'cf-trust-05': { category: 'trust', name: '05 · Beauty Trust', file: 'cf-trust-05.liquid' },
    'cf-trust-06': { category: 'trust', name: '06 · Auto Trust', file: 'cf-trust-06.liquid' },
    'cf-trust-07': { category: 'trust', name: '07 · SaaS Trust', file: 'cf-trust-07.liquid' },
    'cf-trust-08': { category: 'trust', name: '08 · Kids Trust', file: 'cf-trust-08.liquid' },
    'cf-trust-09': { category: 'trust', name: '09 · Furniture Trust', file: 'cf-trust-09.liquid' },
    'cf-trust-10': { category: 'trust', name: '10 · Fitness Trust', file: 'cf-trust-10.liquid' },
    'cf-trust-11': { category: 'trust', name: '11 · Men\'s Trust', file: 'cf-trust-11.liquid' },
    'cf-trust-11-v2': { category: 'trust', name: '11 · Men\'s Trust (v2)', file: 'cf-trust-11-v2.liquid' },
    'cf-trust-11-v3': { category: 'trust', name: '11 · Men\'s Trust (v3)', file: 'cf-trust-11-v3.liquid' },
    'cf-trust-11-v4': { category: 'trust', name: '11 · Men\'s Trust (v4)', file: 'cf-trust-11-v4.liquid' },
    'cf-trust-11-v5': { category: 'trust', name: '11 · Men\'s Trust (v5)', file: 'cf-trust-11-v5.liquid' },
    'cf-trust-11-v6': { category: 'trust', name: '11 · Men\'s Trust (v6)', file: 'cf-trust-11-v6.liquid' },
    'cf-trust-11-v7': { category: 'trust', name: '11 · Men\'s Trust (v7)', file: 'cf-trust-11-v7.liquid' },
    'cf-trust-11-v8': { category: 'trust', name: '11 · Men\'s Trust (v8)', file: 'cf-trust-11-v8.liquid' },
    'cf-trust-11-v9': { category: 'trust', name: '11 · Men\'s Trust (v9)', file: 'cf-trust-11-v9.liquid' },
    'cf-trust-11-v10': { category: 'trust', name: '11 · Men\'s Trust (v10)', file: 'cf-trust-11-v10.liquid' },
    'cf-trust-12': { category: 'trust', name: '12 · Women\'s Trust', file: 'cf-trust-12.liquid' },
    'cf-trust-13': { category: 'trust', name: '13 · Brand Trust', file: 'cf-trust-13.liquid' },

    'cf-announce-01': { category: 'announcement', name: '01 · Gradient Marquee', file: 'cf-announce-01.liquid' },
    'cf-announce-02': { category: 'announcement', name: '02 · Minimal Dark Bar', file: 'cf-announce-02.liquid' },
    'cf-announce-03': { category: 'announcement', name: '03 · Countdown Timer Bar', file: 'cf-announce-03.liquid' },
    'cf-announce-04': { category: 'announcement', name: '04 · Glassmorphism Bar', file: 'cf-announce-04.liquid' },
    'cf-announce-05': { category: 'announcement', name: '05 · Neon Glow Bar', file: 'cf-announce-05.liquid' },
    'cf-announce-06': { category: 'announcement', name: '06 · Emoji Marquee Bar', file: 'cf-announce-06.liquid' },
    'cf-announce-07': { category: 'announcement', name: '07 · Split Promo Bar', file: 'cf-announce-07.liquid' },
    'cf-announce-08': { category: 'announcement', name: '08 · Animated Wave Bar', file: 'cf-announce-08.liquid' },
    'cf-announce-09': { category: 'announcement', name: '09 · Bold Full-Width Bar', file: 'cf-announce-09.liquid' },
    'cf-announce-10': { category: 'announcement', name: '10 · Multi-Line Icon Bar', file: 'cf-announce-10.liquid' },

    'cf-hero-01': { category: 'hero', name: '01 · Gradient Hero', file: 'cf-hero-01.liquid' },
    'cf-hero-02': { category: 'hero', name: '02 · Split Hero', file: 'cf-hero-02.liquid' },
    'cf-hero-03': { category: 'hero', name: '03 · Fullscreen Image Hero', file: 'cf-hero-03.liquid' },
    'cf-hero-04': { category: 'hero', name: '04 · Stats Hero', file: 'cf-hero-04.liquid' },
    'cf-hero-05': { category: 'hero', name: '05 · Gradient Text Hero', file: 'cf-hero-05.liquid' },
    'cf-hero-06': { category: 'hero', name: '06 · Email Capture Hero', file: 'cf-hero-06.liquid' },
    'cf-hero-07': { category: 'hero', name: '07 · Video + Features Hero', file: 'cf-hero-07.liquid' },
    'cf-hero-08': { category: 'hero', name: '08 · Dark SaaS Hero', file: 'cf-hero-08.liquid' },
    'cf-hero-09': { category: 'hero', name: '09 · Flash Sale Hero', file: 'cf-hero-09.liquid' },
    'cf-hero-10': { category: 'hero', name: '10 · Product Showcase Hero', file: 'cf-hero-10.liquid' },
    'cf-cat-01-v10': { category: 'category', name: '01 · Luxury Category (v10)', file: 'cf-cat-01-v10.liquid' },
    'cf-cat-01-v2': { category: 'category', name: '01 · Luxury Category (v2)', file: 'cf-cat-01-v2.liquid' },
    'cf-cat-01-v3': { category: 'category', name: '01 · Luxury Category (v3)', file: 'cf-cat-01-v3.liquid' },
    'cf-cat-01-v4': { category: 'category', name: '01 · Luxury Category (v4)', file: 'cf-cat-01-v4.liquid' },
    'cf-cat-01-v5': { category: 'category', name: '01 · Luxury Category (v5)', file: 'cf-cat-01-v5.liquid' },
    'cf-cat-01-v6': { category: 'category', name: '01 · Luxury Category (v6)', file: 'cf-cat-01-v6.liquid' },
    'cf-cat-01-v7': { category: 'category', name: '01 · Luxury Category (v7)', file: 'cf-cat-01-v7.liquid' },
    'cf-cat-01-v8': { category: 'category', name: '01 · Luxury Category (v8)', file: 'cf-cat-01-v8.liquid' },
    'cf-cat-01-v9': { category: 'category', name: '01 · Luxury Category (v9)', file: 'cf-cat-01-v9.liquid' },
    'cf-cat-13-v10': { category: 'category', name: '13 · Brand Category (v10)', file: 'cf-cat-13-v10.liquid' },
    'cf-cat-13-v2': { category: 'category', name: '13 · Brand Category (v2)', file: 'cf-cat-13-v2.liquid' },
    'cf-cat-13-v3': { category: 'category', name: '13 · Brand Category (v3)', file: 'cf-cat-13-v3.liquid' },
    'cf-cat-13-v4': { category: 'category', name: '13 · Brand Category (v4)', file: 'cf-cat-13-v4.liquid' },
    'cf-cat-13-v5': { category: 'category', name: '13 · Brand Category (v5)', file: 'cf-cat-13-v5.liquid' },
    'cf-cat-13-v6': { category: 'category', name: '13 · Brand Category (v6)', file: 'cf-cat-13-v6.liquid' },
    'cf-cat-13-v7': { category: 'category', name: '13 · Brand Category (v7)', file: 'cf-cat-13-v7.liquid' },
    'cf-cat-13-v8': { category: 'category', name: '13 · Brand Category (v8)', file: 'cf-cat-13-v8.liquid' },
    'cf-cat-13-v9': { category: 'category', name: '13 · Brand Category (v9)', file: 'cf-cat-13-v9.liquid' },
    'cf-feat-01-v10': { category: 'feature', name: '01 · Luxury Featured (v10)', file: 'cf-feat-01-v10.liquid' },
    'cf-feat-01-v2': { category: 'feature', name: '01 · Luxury Featured (v2)', file: 'cf-feat-01-v2.liquid' },
    'cf-feat-01-v3': { category: 'feature', name: '01 · Luxury Featured (v3)', file: 'cf-feat-01-v3.liquid' },
    'cf-feat-01-v4': { category: 'feature', name: '01 · Luxury Featured (v4)', file: 'cf-feat-01-v4.liquid' },
    'cf-feat-01-v5': { category: 'feature', name: '01 · Luxury Featured (v5)', file: 'cf-feat-01-v5.liquid' },
    'cf-feat-01-v6': { category: 'feature', name: '01 · Luxury Featured (v6)', file: 'cf-feat-01-v6.liquid' },
    'cf-feat-01-v7': { category: 'feature', name: '01 · Luxury Featured (v7)', file: 'cf-feat-01-v7.liquid' },
    'cf-feat-01-v8': { category: 'feature', name: '01 · Luxury Featured (v8)', file: 'cf-feat-01-v8.liquid' },
    'cf-feat-01-v9': { category: 'feature', name: '01 · Luxury Featured (v9)', file: 'cf-feat-01-v9.liquid' },
    'cf-feat-13-v10': { category: 'feature', name: '13 · Brand Featured (v10)', file: 'cf-feat-13-v10.liquid' },
    'cf-feat-13-v2': { category: 'feature', name: '13 · Brand Featured (v2)', file: 'cf-feat-13-v2.liquid' },
    'cf-feat-13-v3': { category: 'feature', name: '13 · Brand Featured (v3)', file: 'cf-feat-13-v3.liquid' },
    'cf-feat-13-v4': { category: 'feature', name: '13 · Brand Featured (v4)', file: 'cf-feat-13-v4.liquid' },
    'cf-feat-13-v5': { category: 'feature', name: '13 · Brand Featured (v5)', file: 'cf-feat-13-v5.liquid' },
    'cf-feat-13-v6': { category: 'feature', name: '13 · Brand Featured (v6)', file: 'cf-feat-13-v6.liquid' },
    'cf-feat-13-v7': { category: 'feature', name: '13 · Brand Featured (v7)', file: 'cf-feat-13-v7.liquid' },
    'cf-feat-13-v8': { category: 'feature', name: '13 · Brand Featured (v8)', file: 'cf-feat-13-v8.liquid' },
    'cf-feat-13-v9': { category: 'feature', name: '13 · Brand Featured (v9)', file: 'cf-feat-13-v9.liquid' },
    'cf-header-01-v10': { category: 'header', name: '01 · Luxury Header (v10)', file: 'cf-header-01-v10.liquid' },
    'cf-header-01-v2': { category: 'header', name: '01 · Luxury Header (v2)', file: 'cf-header-01-v2.liquid' },
    'cf-header-01-v3': { category: 'header', name: '01 · Luxury Header (v3)', file: 'cf-header-01-v3.liquid' },
    'cf-header-01-v4': { category: 'header', name: '01 · Luxury Header (v4)', file: 'cf-header-01-v4.liquid' },
    'cf-header-01-v5': { category: 'header', name: '01 · Luxury Header (v5)', file: 'cf-header-01-v5.liquid' },
    'cf-header-01-v6': { category: 'header', name: '01 · Luxury Header (v6)', file: 'cf-header-01-v6.liquid' },
    'cf-header-01-v7': { category: 'header', name: '01 · Luxury Header (v7)', file: 'cf-header-01-v7.liquid' },
    'cf-header-01-v8': { category: 'header', name: '01 · Luxury Header (v8)', file: 'cf-header-01-v8.liquid' },
    'cf-header-01-v9': { category: 'header', name: '01 · Luxury Header (v9)', file: 'cf-header-01-v9.liquid' },
    'cf-header-13-v10': { category: 'header', name: '13 · Brand Header (v10)', file: 'cf-header-13-v10.liquid' },
    'cf-header-13-v2': { category: 'header', name: '13 · Brand Header (v2)', file: 'cf-header-13-v2.liquid' },
    'cf-header-13-v3': { category: 'header', name: '13 · Brand Header (v3)', file: 'cf-header-13-v3.liquid' },
    'cf-header-13-v4': { category: 'header', name: '13 · Brand Header (v4)', file: 'cf-header-13-v4.liquid' },
    'cf-header-13-v5': { category: 'header', name: '13 · Brand Header (v5)', file: 'cf-header-13-v5.liquid' },
    'cf-header-13-v6': { category: 'header', name: '13 · Brand Header (v6)', file: 'cf-header-13-v6.liquid' },
    'cf-header-13-v7': { category: 'header', name: '13 · Brand Header (v7)', file: 'cf-header-13-v7.liquid' },
    'cf-header-13-v8': { category: 'header', name: '13 · Brand Header (v8)', file: 'cf-header-13-v8.liquid' },
    'cf-header-13-v9': { category: 'header', name: '13 · Brand Header (v9)', file: 'cf-header-13-v9.liquid' },
    'cf-marquee-01-v10': { category: 'marquee', name: '01 · Luxury Marquee (v10)', file: 'cf-marquee-01-v10.liquid' },
    'cf-marquee-01-v2': { category: 'marquee', name: '01 · Luxury Marquee (v2)', file: 'cf-marquee-01-v2.liquid' },
    'cf-marquee-01-v3': { category: 'marquee', name: '01 · Luxury Marquee (v3)', file: 'cf-marquee-01-v3.liquid' },
    'cf-marquee-01-v4': { category: 'marquee', name: '01 · Luxury Marquee (v4)', file: 'cf-marquee-01-v4.liquid' },
    'cf-marquee-01-v5': { category: 'marquee', name: '01 · Luxury Marquee (v5)', file: 'cf-marquee-01-v5.liquid' },
    'cf-marquee-01-v6': { category: 'marquee', name: '01 · Luxury Marquee (v6)', file: 'cf-marquee-01-v6.liquid' },
    'cf-marquee-01-v7': { category: 'marquee', name: '01 · Luxury Marquee (v7)', file: 'cf-marquee-01-v7.liquid' },
    'cf-marquee-01-v8': { category: 'marquee', name: '01 · Luxury Marquee (v8)', file: 'cf-marquee-01-v8.liquid' },
    'cf-marquee-01-v9': { category: 'marquee', name: '01 · Luxury Marquee (v9)', file: 'cf-marquee-01-v9.liquid' },
    'cf-marquee-13-v10': { category: 'marquee', name: '13 · Brand Marquee (v10)', file: 'cf-marquee-13-v10.liquid' },
    'cf-marquee-13-v2': { category: 'marquee', name: '13 · Brand Marquee (v2)', file: 'cf-marquee-13-v2.liquid' },
    'cf-marquee-13-v3': { category: 'marquee', name: '13 · Brand Marquee (v3)', file: 'cf-marquee-13-v3.liquid' },
    'cf-marquee-13-v4': { category: 'marquee', name: '13 · Brand Marquee (v4)', file: 'cf-marquee-13-v4.liquid' },
    'cf-marquee-13-v5': { category: 'marquee', name: '13 · Brand Marquee (v5)', file: 'cf-marquee-13-v5.liquid' },
    'cf-marquee-13-v6': { category: 'marquee', name: '13 · Brand Marquee (v6)', file: 'cf-marquee-13-v6.liquid' },
    'cf-marquee-13-v7': { category: 'marquee', name: '13 · Brand Marquee (v7)', file: 'cf-marquee-13-v7.liquid' },
    'cf-marquee-13-v8': { category: 'marquee', name: '13 · Brand Marquee (v8)', file: 'cf-marquee-13-v8.liquid' },
    'cf-marquee-13-v9': { category: 'marquee', name: '13 · Brand Marquee (v9)', file: 'cf-marquee-13-v9.liquid' },
    'cf-promo-01-v10': { category: 'promo', name: '01 · Luxury Promo (v10)', file: 'cf-promo-01-v10.liquid' },
    'cf-promo-01-v2': { category: 'promo', name: '01 · Luxury Promo (v2)', file: 'cf-promo-01-v2.liquid' },
    'cf-promo-01-v3': { category: 'promo', name: '01 · Luxury Promo (v3)', file: 'cf-promo-01-v3.liquid' },
    'cf-promo-01-v4': { category: 'promo', name: '01 · Luxury Promo (v4)', file: 'cf-promo-01-v4.liquid' },
    'cf-promo-01-v5': { category: 'promo', name: '01 · Luxury Promo (v5)', file: 'cf-promo-01-v5.liquid' },
    'cf-promo-01-v6': { category: 'promo', name: '01 · Luxury Promo (v6)', file: 'cf-promo-01-v6.liquid' },
    'cf-promo-01-v7': { category: 'promo', name: '01 · Luxury Promo (v7)', file: 'cf-promo-01-v7.liquid' },
    'cf-promo-01-v8': { category: 'promo', name: '01 · Luxury Promo (v8)', file: 'cf-promo-01-v8.liquid' },
    'cf-promo-01-v9': { category: 'promo', name: '01 · Luxury Promo (v9)', file: 'cf-promo-01-v9.liquid' },
    'cf-promo-13-v10': { category: 'promo', name: '13 · Brand Promo (v10)', file: 'cf-promo-13-v10.liquid' },
    'cf-promo-13-v2': { category: 'promo', name: '13 · Brand Promo (v2)', file: 'cf-promo-13-v2.liquid' },
    'cf-promo-13-v3': { category: 'promo', name: '13 · Brand Promo (v3)', file: 'cf-promo-13-v3.liquid' },
    'cf-promo-13-v4': { category: 'promo', name: '13 · Brand Promo (v4)', file: 'cf-promo-13-v4.liquid' },
    'cf-promo-13-v5': { category: 'promo', name: '13 · Brand Promo (v5)', file: 'cf-promo-13-v5.liquid' },
    'cf-promo-13-v6': { category: 'promo', name: '13 · Brand Promo (v6)', file: 'cf-promo-13-v6.liquid' },
    'cf-promo-13-v7': { category: 'promo', name: '13 · Brand Promo (v7)', file: 'cf-promo-13-v7.liquid' },
    'cf-promo-13-v8': { category: 'promo', name: '13 · Brand Promo (v8)', file: 'cf-promo-13-v8.liquid' },
    'cf-promo-13-v9': { category: 'promo', name: '13 · Brand Promo (v9)', file: 'cf-promo-13-v9.liquid' },
    'cf-snack-01-v10': { category: 'snack', name: '01 · Luxury Snack (v10)', file: 'cf-snack-01-v10.liquid' },
    'cf-snack-01-v2': { category: 'snack', name: '01 · Luxury Snack (v2)', file: 'cf-snack-01-v2.liquid' },
    'cf-snack-01-v3': { category: 'snack', name: '01 · Luxury Snack (v3)', file: 'cf-snack-01-v3.liquid' },
    'cf-snack-01-v4': { category: 'snack', name: '01 · Luxury Snack (v4)', file: 'cf-snack-01-v4.liquid' },
    'cf-snack-01-v5': { category: 'snack', name: '01 · Luxury Snack (v5)', file: 'cf-snack-01-v5.liquid' },
    'cf-snack-01-v6': { category: 'snack', name: '01 · Luxury Snack (v6)', file: 'cf-snack-01-v6.liquid' },
    'cf-snack-01-v7': { category: 'snack', name: '01 · Luxury Snack (v7)', file: 'cf-snack-01-v7.liquid' },
    'cf-snack-01-v8': { category: 'snack', name: '01 · Luxury Snack (v8)', file: 'cf-snack-01-v8.liquid' },
    'cf-snack-01-v9': { category: 'snack', name: '01 · Luxury Snack (v9)', file: 'cf-snack-01-v9.liquid' },
    'cf-snack-13-v10': { category: 'snack', name: '13 · Brand Snack (v10)', file: 'cf-snack-13-v10.liquid' },
    'cf-snack-13-v2': { category: 'snack', name: '13 · Brand Snack (v2)', file: 'cf-snack-13-v2.liquid' },
    'cf-snack-13-v3': { category: 'snack', name: '13 · Brand Snack (v3)', file: 'cf-snack-13-v3.liquid' },
    'cf-snack-13-v4': { category: 'snack', name: '13 · Brand Snack (v4)', file: 'cf-snack-13-v4.liquid' },
    'cf-snack-13-v5': { category: 'snack', name: '13 · Brand Snack (v5)', file: 'cf-snack-13-v5.liquid' },
    'cf-snack-13-v6': { category: 'snack', name: '13 · Brand Snack (v6)', file: 'cf-snack-13-v6.liquid' },
    'cf-snack-13-v7': { category: 'snack', name: '13 · Brand Snack (v7)', file: 'cf-snack-13-v7.liquid' },
    'cf-snack-13-v8': { category: 'snack', name: '13 · Brand Snack (v8)', file: 'cf-snack-13-v8.liquid' },
    'cf-snack-13-v9': { category: 'snack', name: '13 · Brand Snack (v9)', file: 'cf-snack-13-v9.liquid' },
    'cf-trust-01-v10': { category: 'trust', name: '01 · Luxury Trust (v10)', file: 'cf-trust-01-v10.liquid' },
    'cf-trust-01-v2': { category: 'trust', name: '01 · Luxury Trust (v2)', file: 'cf-trust-01-v2.liquid' },
    'cf-trust-01-v3': { category: 'trust', name: '01 · Luxury Trust (v3)', file: 'cf-trust-01-v3.liquid' },
    'cf-trust-01-v4': { category: 'trust', name: '01 · Luxury Trust (v4)', file: 'cf-trust-01-v4.liquid' },
    'cf-trust-01-v5': { category: 'trust', name: '01 · Luxury Trust (v5)', file: 'cf-trust-01-v5.liquid' },
    'cf-trust-01-v6': { category: 'trust', name: '01 · Luxury Trust (v6)', file: 'cf-trust-01-v6.liquid' },
    'cf-trust-01-v7': { category: 'trust', name: '01 · Luxury Trust (v7)', file: 'cf-trust-01-v7.liquid' },
    'cf-trust-01-v8': { category: 'trust', name: '01 · Luxury Trust (v8)', file: 'cf-trust-01-v8.liquid' },
    'cf-trust-01-v9': { category: 'trust', name: '01 · Luxury Trust (v9)', file: 'cf-trust-01-v9.liquid' },
    'cf-trust-13-v10': { category: 'trust', name: '13 · Brand Trust (v10)', file: 'cf-trust-13-v10.liquid' },
    'cf-trust-13-v2': { category: 'trust', name: '13 · Brand Trust (v2)', file: 'cf-trust-13-v2.liquid' },
    'cf-trust-13-v3': { category: 'trust', name: '13 · Brand Trust (v3)', file: 'cf-trust-13-v3.liquid' },
    'cf-trust-13-v4': { category: 'trust', name: '13 · Brand Trust (v4)', file: 'cf-trust-13-v4.liquid' },
    'cf-trust-13-v5': { category: 'trust', name: '13 · Brand Trust (v5)', file: 'cf-trust-13-v5.liquid' },
    'cf-trust-13-v6': { category: 'trust', name: '13 · Brand Trust (v6)', file: 'cf-trust-13-v6.liquid' },
    'cf-trust-13-v7': { category: 'trust', name: '13 · Brand Trust (v7)', file: 'cf-trust-13-v7.liquid' },
    'cf-trust-13-v8': { category: 'trust', name: '13 · Brand Trust (v8)', file: 'cf-trust-13-v8.liquid' },
    'cf-trust-13-v9': { category: 'trust', name: '13 · Brand Trust (v9)', file: 'cf-trust-13-v9.liquid' },

    // ── CRO Home Sections ────────────────────────────────────────
    'cf-cro-hero': { category: 'cro-home', name: 'CRO · Problem/Solution Hero', file: 'cf-cro-hero.liquid' },
    'cf-cro-hero-v2': { category: 'cro-home', name: 'CRO · Centered Hero v2', file: 'cf-cro-hero-v2.liquid' },
    'cf-cro-hero-v3': { category: 'cro-home', name: 'CRO · Dark Image Hero v3', file: 'cf-cro-hero-v3.liquid' },
    'cf-cro-offer-grid': { category: 'cro-home', name: 'CRO · Buy More Save More', file: 'cf-cro-offer-grid.liquid' },
    'cf-cro-offer-grid-v2': { category: 'cro-home', name: 'CRO · Pricing Tiers v2', file: 'cf-cro-offer-grid-v2.liquid' },
    'cf-cro-offer-grid-v3': { category: 'cro-home', name: 'CRO · Radio Offer Stack v3', file: 'cf-cro-offer-grid-v3.liquid' },
    'cf-cro-social-proof': { category: 'cro-home', name: 'CRO · Social Proof', file: 'cf-cro-social-proof.liquid' },
    'cf-cro-social-proof-v2': { category: 'cro-home', name: 'CRO · Reviews Carousel v2', file: 'cf-cro-social-proof-v2.liquid' },
    'cf-cro-social-proof-v3': { category: 'cro-home', name: 'CRO · Featured Review v3', file: 'cf-cro-social-proof-v3.liquid' },
    'cf-cro-benefits': { category: 'cro-home', name: 'CRO · Trust Benefits Bar', file: 'cf-cro-benefits.liquid' },
    'cf-cro-benefits-v2': { category: 'cro-home', name: 'CRO · Scrolling Trust Bar v2', file: 'cf-cro-benefits-v2.liquid' },
    'cf-cro-benefits-v3': { category: 'cro-home', name: 'CRO · Benefit Cards v3', file: 'cf-cro-benefits-v3.liquid' },
    'cf-cro-countdown': { category: 'cro-home', name: 'CRO · Countdown Timer', file: 'cf-cro-countdown.liquid' },
    'cf-cro-countdown-v2': { category: 'cro-home', name: 'CRO · Gradient Countdown v2', file: 'cf-cro-countdown-v2.liquid' },
    'cf-cro-countdown-v3': { category: 'cro-home', name: 'CRO · Split Countdown v3', file: 'cf-cro-countdown-v3.liquid' },

    // ── CRO Product Sections ──────────────────────────────────────
    'cf-cro-mini-pdp': { category: 'cro-product', name: 'CRO · Featured Product', file: 'cf-cro-mini-pdp.liquid' },
    'cf-cro-mini-pdp-v2': { category: 'cro-product', name: 'CRO · Product Gallery v2', file: 'cf-cro-mini-pdp-v2.liquid' },
    'cf-cro-faq': { category: 'cro-product', name: 'CRO · FAQ Accordion', file: 'cf-cro-faq.liquid' },
    'cf-cro-faq-v2': { category: 'cro-product', name: 'CRO · FAQ Split Layout v2', file: 'cf-cro-faq-v2.liquid' },
    'cf-cro-comparison': { category: 'cro-product', name: 'CRO · Us vs Them', file: 'cf-cro-comparison.liquid' },
    'cf-cro-comparison-v2': { category: 'cro-product', name: 'CRO · Side-by-Side Cards v2', file: 'cf-cro-comparison-v2.liquid' },
    'cf-cro-bundle': { category: 'cro-product', name: 'CRO · Bundle Upsell', file: 'cf-cro-bundle.liquid' },
    'cf-cro-bundle-v2': { category: 'cro-product', name: 'CRO · Bundle Split v2', file: 'cf-cro-bundle-v2.liquid' },
};

export function getSectionsByCategory(categoryId) {
    return Object.entries(SECTION_FILES)
        .filter(([_, meta]) => meta.category === categoryId)
        .map(([id, meta]) => ({ id, ...meta }));
}

export function getCategoriesWithCounts() {
    return SECTION_CATEGORIES.map(cat => ({
        ...cat,
        count: Object.values(SECTION_FILES).filter(s => s.category === cat.id).length,
    }));
}
