export const SECTION_CATEGORIES = [
    { id: 'header', name: 'Header', description: 'Navigation bars and branding', icon: 'Layout' },
    { id: 'marquee', name: 'Marquee / Tickers', description: 'Infinite scrolling announcement bands', icon: 'Type' },
    { id: 'promo', name: 'Promo Posters', description: 'Large format promotional banners', icon: 'Image' },
    { id: 'snack', name: 'Promo Code Snacks', description: 'Compact discount code and offer bars', icon: 'Tag' },
    { id: 'category', name: 'Category Sections', description: 'Collection grids and carousels', icon: 'Grid' },
    { id: 'feature', name: 'Featured Collections', description: 'Product grids and sliders', icon: 'ShoppingBag' },
    { id: 'trust', name: 'Trust Badges', description: 'Guarantees and value props', icon: 'Shield' },
    { id: 'announcement', name: 'Announcement Bars', description: '10 creative announcement styles', icon: 'Megaphone' },
    { id: 'hero', name: 'Hero Sections', description: '10 premium hero banners', icon: 'Image' }
];

export const SECTION_FILES = {
    'cf-head-01': { category: 'header', name: '01 · Luxury Header', file: 'cf-head-01.liquid' },
    'cf-head-02': { category: 'header', name: '02 · Streetwear Header', file: 'cf-head-02.liquid' },
    'cf-head-03': { category: 'header', name: '03 · Tech Header', file: 'cf-head-03.liquid' },
    'cf-head-04': { category: 'header', name: '04 · Health Header', file: 'cf-head-04.liquid' },
    'cf-head-05': { category: 'header', name: '05 · Beauty Header', file: 'cf-head-05.liquid' },
    'cf-head-06': { category: 'header', name: '06 · Automotive Header', file: 'cf-head-06.liquid' },
    'cf-head-07': { category: 'header', name: '07 · SaaS Header', file: 'cf-head-07.liquid' },
    'cf-head-08': { category: 'header', name: '08 · Kids Header', file: 'cf-head-08.liquid' },
    'cf-head-09': { category: 'header', name: '09 · Furniture Header', file: 'cf-head-09.liquid' },
    'cf-head-10': { category: 'header', name: '10 · Fitness Header', file: 'cf-head-10.liquid' },
    'cf-head-11': { category: 'header', name: '11 · Men\'s Header', file: 'cf-head-11.liquid' },
    'cf-head-11-v2': { category: 'header', name: '11 · Men\'s Header (v2)', file: 'cf-head-11-v2.liquid' },
    'cf-head-11-v3': { category: 'header', name: '11 · Men\'s Header (v3)', file: 'cf-head-11-v3.liquid' },
    'cf-head-11-v4': { category: 'header', name: '11 · Men\'s Header (v4)', file: 'cf-head-11-v4.liquid' },
    'cf-head-11-v5': { category: 'header', name: '11 · Men\'s Header (v5)', file: 'cf-head-11-v5.liquid' },
    'cf-head-11-v6': { category: 'header', name: '11 · Men\'s Header (v6)', file: 'cf-head-11-v6.liquid' },
    'cf-head-11-v7': { category: 'header', name: '11 · Men\'s Header (v7)', file: 'cf-head-11-v7.liquid' },
    'cf-head-11-v8': { category: 'header', name: '11 · Men\'s Header (v8)', file: 'cf-head-11-v8.liquid' },
    'cf-head-11-v9': { category: 'header', name: '11 · Men\'s Header (v9)', file: 'cf-head-11-v9.liquid' },
    'cf-head-11-v10': { category: 'header', name: '11 · Men\'s Header (v10)', file: 'cf-head-11-v10.liquid' },
    'cf-head-12': { category: 'header', name: '12 · Women\'s Header', file: 'cf-head-12.liquid' },
    'cf-head-13': { category: 'header', name: '13 · Brand Header', file: 'cf-head-13.liquid' },

    'cf-marquee-01': { category: 'marquee', name: '01 · Luxury Marquee', file: 'cf-marquee-01.liquid' },
    'cf-marquee-02': { category: 'marquee', name: '02 · Streetwear Marquee', file: 'cf-marquee-02.liquid' },
    'cf-marquee-03': { category: 'marquee', name: '03 · Tech Marquee', file: 'cf-marquee-03.liquid' },
    'cf-marquee-04': { category: 'marquee', name: '04 · Health Marquee', file: 'cf-marquee-04.liquid' },
    'cf-marquee-05': { category: 'marquee', name: '05 · Beauty Marquee', file: 'cf-marquee-05.liquid' },
    'cf-marquee-06': { category: 'marquee', name: '06 · Auto Marquee', file: 'cf-marquee-06.liquid' },
    'cf-marquee-07': { category: 'marquee', name: '07 · SaaS Marquee', file: 'cf-marquee-07.liquid' },
    'cf-marquee-08': { category: 'marquee', name: '08 · Kids Marquee', file: 'cf-marquee-08.liquid' },
    'cf-marquee-09': { category: 'marquee', name: '09 · Furniture Marquee', file: 'cf-marquee-09.liquid' },
    'cf-marquee-10': { category: 'marquee', name: '10 · Fitness Marquee', file: 'cf-marquee-10.liquid' },
    'cf-marquee-11': { category: 'marquee', name: '11 · Men\'s Marquee', file: 'cf-marquee-11.liquid' },
    'cf-marquee-11-v2': { category: 'marquee', name: '11 · Men\'s Marquee (v2)', file: 'cf-marquee-11-v2.liquid' },
    'cf-marquee-11-v3': { category: 'marquee', name: '11 · Men\'s Marquee (v3)', file: 'cf-marquee-11-v3.liquid' },
    'cf-marquee-11-v4': { category: 'marquee', name: '11 · Men\'s Marquee (v4)', file: 'cf-marquee-11-v4.liquid' },
    'cf-marquee-11-v5': { category: 'marquee', name: '11 · Men\'s Marquee (v5)', file: 'cf-marquee-11-v5.liquid' },
    'cf-marquee-11-v6': { category: 'marquee', name: '11 · Men\'s Marquee (v6)', file: 'cf-marquee-11-v6.liquid' },
    'cf-marquee-11-v7': { category: 'marquee', name: '11 · Men\'s Marquee (v7)', file: 'cf-marquee-11-v7.liquid' },
    'cf-marquee-11-v8': { category: 'marquee', name: '11 · Men\'s Marquee (v8)', file: 'cf-marquee-11-v8.liquid' },
    'cf-marquee-11-v9': { category: 'marquee', name: '11 · Men\'s Marquee (v9)', file: 'cf-marquee-11-v9.liquid' },
    'cf-marquee-11-v10': { category: 'marquee', name: '11 · Men\'s Marquee (v10)', file: 'cf-marquee-11-v10.liquid' },
    'cf-marquee-12': { category: 'marquee', name: '12 · Women\'s Marquee', file: 'cf-marquee-12.liquid' },
    'cf-marquee-13': { category: 'marquee', name: '13 · Brand Marquee', file: 'cf-marquee-13.liquid' },

    'cf-promo-01': { category: 'promo', name: '01 · Luxury Promo', file: 'cf-promo-01.liquid' },
    'cf-promo-02': { category: 'promo', name: '02 · Streetwear Promo', file: 'cf-promo-02.liquid' },
    'cf-promo-03': { category: 'promo', name: '03 · Tech Promo', file: 'cf-promo-03.liquid' },
    'cf-promo-04': { category: 'promo', name: '04 · Health Promo', file: 'cf-promo-04.liquid' },
    'cf-promo-05': { category: 'promo', name: '05 · Beauty Promo', file: 'cf-promo-05.liquid' },
    'cf-promo-06': { category: 'promo', name: '06 · Auto Promo', file: 'cf-promo-06.liquid' },
    'cf-promo-07': { category: 'promo', name: '07 · SaaS Promo', file: 'cf-promo-07.liquid' },
    'cf-promo-08': { category: 'promo', name: '08 · Kids Promo', file: 'cf-promo-08.liquid' },
    'cf-promo-09': { category: 'promo', name: '09 · Furniture Promo', file: 'cf-promo-09.liquid' },
    'cf-promo-10': { category: 'promo', name: '10 · Fitness Promo', file: 'cf-promo-10.liquid' },
    'cf-promo-11': { category: 'promo', name: '11 · Men\'s Promo', file: 'cf-promo-11.liquid' },
    'cf-promo-11-v2': { category: 'promo', name: '11 · Men\'s Promo (v2)', file: 'cf-promo-11-v2.liquid' },
    'cf-promo-11-v3': { category: 'promo', name: '11 · Men\'s Promo (v3)', file: 'cf-promo-11-v3.liquid' },
    'cf-promo-11-v4': { category: 'promo', name: '11 · Men\'s Promo (v4)', file: 'cf-promo-11-v4.liquid' },
    'cf-promo-11-v5': { category: 'promo', name: '11 · Men\'s Promo (v5)', file: 'cf-promo-11-v5.liquid' },
    'cf-promo-11-v6': { category: 'promo', name: '11 · Men\'s Promo (v6)', file: 'cf-promo-11-v6.liquid' },
    'cf-promo-11-v7': { category: 'promo', name: '11 · Men\'s Promo (v7)', file: 'cf-promo-11-v7.liquid' },
    'cf-promo-11-v8': { category: 'promo', name: '11 · Men\'s Promo (v8)', file: 'cf-promo-11-v8.liquid' },
    'cf-promo-11-v9': { category: 'promo', name: '11 · Men\'s Promo (v9)', file: 'cf-promo-11-v9.liquid' },
    'cf-promo-11-v10': { category: 'promo', name: '11 · Men\'s Promo (v10)', file: 'cf-promo-11-v10.liquid' },
    'cf-promo-12': { category: 'promo', name: '12 · Women\'s Promo', file: 'cf-promo-12.liquid' },
    'cf-promo-13': { category: 'promo', name: '13 · Brand Promo', file: 'cf-promo-13.liquid' },

    'cf-snack-01': { category: 'snack', name: '01 · Luxury Snack', file: 'cf-snack-01.liquid' },
    'cf-snack-02': { category: 'snack', name: '02 · Streetwear Snack', file: 'cf-snack-02.liquid' },
    'cf-snack-03': { category: 'snack', name: '03 · Tech Snack', file: 'cf-snack-03.liquid' },
    'cf-snack-04': { category: 'snack', name: '04 · Health Snack', file: 'cf-snack-04.liquid' },
    'cf-snack-05': { category: 'snack', name: '05 · Beauty Snack', file: 'cf-snack-05.liquid' },
    'cf-snack-06': { category: 'snack', name: '06 · Auto Snack', file: 'cf-snack-06.liquid' },
    'cf-snack-07': { category: 'snack', name: '07 · SaaS Snack', file: 'cf-snack-07.liquid' },
    'cf-snack-08': { category: 'snack', name: '08 · Kids Snack', file: 'cf-snack-08.liquid' },
    'cf-snack-09': { category: 'snack', name: '09 · Furniture Snack', file: 'cf-snack-09.liquid' },
    'cf-snack-10': { category: 'snack', name: '10 · Fitness Snack', file: 'cf-snack-10.liquid' },
    'cf-snack-11': { category: 'snack', name: '11 · Men\'s Snack', file: 'cf-snack-11.liquid' },
    'cf-snack-12': { category: 'snack', name: '12 · Women\'s Snack', file: 'cf-snack-12.liquid' },
    'cf-snack-13': { category: 'snack', name: '13 · Brand Snack', file: 'cf-snack-13.liquid' },

    'cf-category-01': { category: 'category', name: '01 · Luxury Categories', file: 'cf-category-01.liquid' },
    'cf-category-02': { category: 'category', name: '02 · Streetwear Categories', file: 'cf-category-02.liquid' },
    'cf-category-03': { category: 'category', name: '03 · Tech Categories', file: 'cf-category-03.liquid' },
    'cf-category-04': { category: 'category', name: '04 · Health Categories', file: 'cf-category-04.liquid' },
    'cf-category-05': { category: 'category', name: '05 · Beauty Categories', file: 'cf-category-05.liquid' },
    'cf-category-06': { category: 'category', name: '06 · Auto Categories', file: 'cf-category-06.liquid' },
    'cf-category-07': { category: 'category', name: '07 · SaaS Categories', file: 'cf-category-07.liquid' },
    'cf-category-08': { category: 'category', name: '08 · Kids Categories', file: 'cf-category-08.liquid' },
    'cf-category-09': { category: 'category', name: '09 · Furniture Categories', file: 'cf-category-09.liquid' },
    'cf-category-10': { category: 'category', name: '10 · Fitness Categories', file: 'cf-category-10.liquid' },
    'cf-category-11': { category: 'category', name: '11 · Men\'s Categories', file: 'cf-category-11.liquid' },
    'cf-category-12': { category: 'category', name: '12 · Women\'s Categories', file: 'cf-category-12.liquid' },
    'cf-category-13': { category: 'category', name: '13 · Brand Categories', file: 'cf-cat-13.liquid' },

    'cf-feature-01': { category: 'feature', name: '01 · Luxury Lookbook', file: 'cf-feature-01.liquid' },
    'cf-feature-02': { category: 'feature', name: '02 · Streetwear Drop', file: 'cf-feature-02.liquid' },
    'cf-feature-03': { category: 'feature', name: '03 · Tech Showcase', file: 'cf-feature-03.liquid' },
    'cf-feature-04': { category: 'feature', name: '04 · Health Carousel', file: 'cf-feature-04.liquid' },
    'cf-feature-05': { category: 'feature', name: '05 · Beauty Picks', file: 'cf-feature-05.liquid' },
    'cf-feature-06': { category: 'feature', name: '06 · Auto Parts', file: 'cf-feature-06.liquid' },
    'cf-feature-07': { category: 'feature', name: '07 · SaaS Plans', file: 'cf-feature-07.liquid' },
    'cf-feature-08': { category: 'feature', name: '08 · Kids Toys', file: 'cf-feature-08.liquid' },
    'cf-feature-09': { category: 'feature', name: '09 · Furniture Gallery', file: 'cf-feature-09.liquid' },
    'cf-feature-10': { category: 'feature', name: '10 · Fitness Gear', file: 'cf-feature-10.liquid' },
    'cf-feature-11': { category: 'feature', name: '11 · Men\'s Featured', file: 'cf-feature-11.liquid' },
    'cf-feature-12': { category: 'feature', name: '12 · Women\'s Featured', file: 'cf-feature-12.liquid' },
    'cf-feature-13': { category: 'feature', name: '13 · Brand Featured', file: 'cf-feature-13.liquid' },

    'cf-trust-01': { category: 'trust', name: '01 · Luxury Trust', file: 'cf-trust-01.liquid' },
    'cf-trust-02': { category: 'trust', name: '02 · Streetwear Trust', file: 'cf-trust-02.liquid' },
    'cf-trust-03': { category: 'trust', name: '03 · Tech Trust', file: 'cf-trust-03.liquid' },
    'cf-trust-04': { category: 'trust', name: '04 · Health Trust', file: 'cf-trust-04.liquid' },
    'cf-trust-05': { category: 'trust', name: '05 · Beauty Trust', file: 'cf-trust-05.liquid' },
    'cf-trust-06': { category: 'trust', name: '06 · Auto Trust', file: 'cf-trust-06.liquid' },
    'cf-trust-07': { category: 'trust', name: '07 · SaaS Trust', file: 'cf-trust-07.liquid' },
    'cf-trust-08': { category: 'trust', name: '08 · Kids Trust', file: 'cf-trust-08.liquid' },
    'cf-trust-09': { category: 'trust', name: '09 · Furniture Trust', file: 'cf-trust-09.liquid' },
    'cf-trust-10': { category: 'trust', name: '10 · Fitness Trust', file: 'cf-trust-10.liquid' },
    'cf-trust-11': { category: 'trust', name: '11 · Men\'s Trust', file: 'cf-trust-11.liquid' },
    'cf-trust-12': { category: 'trust', name: '12 · Women\'s Trust', file: 'cf-trust-12.liquid' },
    'cf-trust-13': { category: 'trust', name: '13 · Brand Trust', file: 'cf-trust-13.liquid' },

    'cf-announce-01': { category: 'announcement', name: '01 · Gradient Marquee', file: 'cf-announce-01.liquid' },
    'cf-announce-02': { category: 'announcement', name: '02 · Minimal Dark Bar', file: 'cf-announce-02.liquid' },
    'cf-announce-03': { category: 'announcement', name: '03 · Countdown Timer Bar', file: 'cf-announce-03.liquid' },
    'cf-announce-04': { category: 'announcement', name: '04 · Glassmorphism Bar', file: 'cf-announce-04.liquid' },
    'cf-announce-05': { category: 'announcement', name: '05 · Neon Glow Bar', file: 'cf-announce-05.liquid' },
    'cf-announce-06': { category: 'announcement', name: '06 · Emoji Marquee Bar', file: 'cf-announce-06.liquid' },
    'cf-announce-07': { category: 'announcement', name: '07 · Split Promo Bar', file: 'cf-announce-07.liquid' },
    'cf-announce-08': { category: 'announcement', name: '08 · Animated Wave Bar', file: 'cf-announce-08.liquid' },
    'cf-announce-09': { category: 'announcement', name: '09 · Bold Full-Width Bar', file: 'cf-announce-09.liquid' },
    'cf-announce-10': { category: 'announcement', name: '10 · Multi-Line Icon Bar', file: 'cf-announce-10.liquid' },

    'cf-hero-01': { category: 'hero', name: '01 · Gradient Hero', file: 'cf-hero-01.liquid' },
    'cf-hero-02': { category: 'hero', name: '02 · Split Hero', file: 'cf-hero-02.liquid' },
    'cf-hero-03': { category: 'hero', name: '03 · Fullscreen Image Hero', file: 'cf-hero-03.liquid' },
    'cf-hero-04': { category: 'hero', name: '04 · Stats Hero', file: 'cf-hero-04.liquid' },
    'cf-hero-05': { category: 'hero', name: '05 · Gradient Text Hero', file: 'cf-hero-05.liquid' },
    'cf-hero-06': { category: 'hero', name: '06 · Email Capture Hero', file: 'cf-hero-06.liquid' },
    'cf-hero-07': { category: 'hero', name: '07 · Video + Features Hero', file: 'cf-hero-07.liquid' },
    'cf-hero-08': { category: 'hero', name: '08 · Dark SaaS Hero', file: 'cf-hero-08.liquid' },
    'cf-hero-09': { category: 'hero', name: '09 · Flash Sale Hero', file: 'cf-hero-09.liquid' },
    'cf-hero-10': { category: 'hero', name: '10 · Product Showcase Hero', file: 'cf-hero-10.liquid' },
};

export function getSectionsByCategory(categoryId) {
    return Object.entries(SECTION_FILES)
        .filter(([_, meta]) => meta.category === categoryId)
        .map(([id, meta]) => ({ id, ...meta }));
}

export function getCategoriesWithCounts() {
    return SECTION_CATEGORIES.map(cat => ({
        ...cat,
        count: Object.values(SECTION_FILES).filter(s => s.category === cat.id).length,
    }));
}
