export const SECTION_FILES = {
    'announcement-bar': { category: 'content', name: 'Announcement Bar', file: 'announcement-bar.liquid' },
    'apps': { category: 'content', name: 'Apps', file: 'apps.liquid' },
    'blog-post-slider': { category: 'hero', name: 'Blog Post Slider', file: 'blog-post-slider.liquid' },
    'blog-posts-list': { category: 'content', name: 'Blog Posts List', file: 'blog-posts-list.liquid' },
    'brand-slider-2': { category: 'hero', name: 'Brand Slider 2', file: 'brand-slider-2.liquid' },
    'brand-slider': { category: 'hero', name: 'Brand Slider', file: 'brand-slider.liquid' },
    'brand-tab-block': { category: 'brand', name: 'Brand Tab Block', file: 'brand-tab-block.liquid' },
    'bulk-quick-order-list': { category: 'content', name: 'Bulk Quick Order List', file: 'bulk-quick-order-list.liquid' },
    'cart-icon-bubble': { category: 'content', name: 'Cart Icon Bubble', file: 'cart-icon-bubble.liquid' },
    'cart-live-region-text': { category: 'content', name: 'Cart Live Region Text', file: 'cart-live-region-text.liquid' },
    'cart-notification-button': { category: 'content', name: 'Cart Notification Button', file: 'cart-notification-button.liquid' },
    'cart-notification-product': { category: 'product', name: 'Cart Notification Product', file: 'cart-notification-product.liquid' },
    'collapsible-content': { category: 'content', name: 'Collapsible Content', file: 'collapsible-content.liquid' },
    'collection-list': { category: 'collection', name: 'Collection List', file: 'collection-list.liquid' },
    'counter-positions-image-banner': { category: 'hero', name: 'Counter Positions Image Banner', file: 'counter-positions-image-banner.liquid' },
    'custom-image-banner-2': { category: 'hero', name: 'Custom Image Banner 2', file: 'custom-image-banner-2.liquid' },
    'custom-image-banner': { category: 'hero', name: 'Custom Image Banner', file: 'custom-image-banner.liquid' },
    'custom-liquid': { category: 'content', name: 'Custom Liquid', file: 'custom-liquid.liquid' },
    'custom-press-banner': { category: 'hero', name: 'Custom Press Banner', file: 'custom-press-banner.liquid' },
    'custom-product-widget': { category: 'product', name: 'Custom Product Widget', file: 'custom-product-widget.liquid' },
    'custom-section': { category: 'content', name: 'Custom Section', file: 'custom-section.liquid' },
    'custom-service-block': { category: 'brand', name: 'Custom Service Block', file: 'custom-service-block.liquid' },
    'custom-text-block': { category: 'content', name: 'Custom Text Block', file: 'custom-text-block.liquid' },
    'customer-review-block': { category: 'testimonial', name: 'Customer Review Block', file: 'customer-review-block.liquid' },
    'customer-testimonial': { category: 'testimonial', name: 'Customer Testimonial', file: 'customer-testimonial.liquid' },
    'faqs': { category: 'faq', name: 'Faqs', file: 'faqs.liquid' },
    'featured-blog': { category: 'content', name: 'Featured Blog', file: 'featured-blog.liquid' },
    'featured-collection': { category: 'collection', name: 'Featured Collection', file: 'featured-collection.liquid' },
    'featured-product-unsymmetrical': { category: 'product', name: 'Featured Product Unsymmetrical', file: 'featured-product-unsymmetrical.liquid' },
    'featured-product': { category: 'product', name: 'Featured Product', file: 'featured-product.liquid' },
    'footer-01': { category: 'footer', name: 'Footer 01', file: 'footer-01.liquid' },
    'footer-02': { category: 'footer', name: 'Footer 02', file: 'footer-02.liquid' },
    'footer-03': { category: 'footer', name: 'Footer 03', file: 'footer-03.liquid' },
    'footer-04': { category: 'footer', name: 'Footer 04', file: 'footer-04.liquid' },
    'footer-05': { category: 'footer', name: 'Footer 05', file: 'footer-05.liquid' },
    'footer-06': { category: 'footer', name: 'Footer 06', file: 'footer-06.liquid' },
    'footer-07': { category: 'footer', name: 'Footer 07', file: 'footer-07.liquid' },
    'google-map': { category: 'content', name: 'Google Map', file: 'google-map.liquid' },
    'halo-navigation-mobile-2': { category: 'content', name: 'Halo Navigation Mobile 2', file: 'halo-navigation-mobile-2.liquid' },
    'halo-navigation-mobile-3': { category: 'content', name: 'Halo Navigation Mobile 3', file: 'halo-navigation-mobile-3.liquid' },
    'halo-navigation-mobile': { category: 'content', name: 'Halo Navigation Mobile', file: 'halo-navigation-mobile.liquid' },
    'halo-toolbar-mobile': { category: 'content', name: 'Halo Toolbar Mobile', file: 'halo-toolbar-mobile.liquid' },
    'header-advanced': { category: 'header', name: 'Header Advanced', file: 'header-advanced.liquid' },
    'header-basic': { category: 'header', name: 'Header Basic', file: 'header-basic.liquid' },
    'header-classic': { category: 'header', name: 'Header Classic', file: 'header-classic.liquid' },
    'header-minimal': { category: 'header', name: 'Header Minimal', file: 'header-minimal.liquid' },
    'header-mobile': { category: 'header', name: 'Header Mobile', file: 'header-mobile.liquid' },
    'header-nav-multi-site': { category: 'header', name: 'Header Nav Multi Site', file: 'header-nav-multi-site.liquid' },
    'header-navigation-basic': { category: 'header', name: 'Header Navigation Basic', file: 'header-navigation-basic.liquid' },
    'header-navigation-compact': { category: 'header', name: 'Header Navigation Compact', file: 'header-navigation-compact.liquid' },
    'header-navigation-full-elements': { category: 'header', name: 'Header Navigation Full Elements', file: 'header-navigation-full-elements.liquid' },
    'header-navigation-hamburger': { category: 'header', name: 'Header Navigation Hamburger', file: 'header-navigation-hamburger.liquid' },
    'header-navigation-left-aligned': { category: 'header', name: 'Header Navigation Left Aligned', file: 'header-navigation-left-aligned.liquid' },
    'header-navigation-plain': { category: 'header', name: 'Header Navigation Plain', file: 'header-navigation-plain.liquid' },
    'header-navigation-utility': { category: 'header', name: 'Header Navigation Utility', file: 'header-navigation-utility.liquid' },
    'header-navigation-vertical-menu': { category: 'header', name: 'Header Navigation Vertical Menu', file: 'header-navigation-vertical-menu.liquid' },
    'header-simple': { category: 'header', name: 'Header Simple', file: 'header-simple.liquid' },
    'header-single-line': { category: 'header', name: 'Header Single Line', file: 'header-single-line.liquid' },
    'header-utility': { category: 'header', name: 'Header Utility', file: 'header-utility.liquid' },
    'image-banner': { category: 'hero', name: 'Image Banner', file: 'image-banner.liquid' },
    'image-comparison': { category: 'content', name: 'Image Comparison', file: 'image-comparison.liquid' },
    'instagram-grid': { category: 'social', name: 'Instagram Grid', file: 'instagram-grid.liquid' },
    'instagram-special': { category: 'social', name: 'Instagram Special', file: 'instagram-special.liquid' },
    'instagram': { category: 'social', name: 'Instagram', file: 'instagram.liquid' },
    'large-lookbook-banners': { category: 'hero', name: 'Large Lookbook Banners', file: 'large-lookbook-banners.liquid' },
    'lookbook-with-collection': { category: 'collection', name: 'Lookbook With Collection', file: 'lookbook-with-collection.liquid' },
    'main-404': { category: 'content', name: 'Main 404', file: 'main-404.liquid' },
    'main-about-1-page': { category: 'content', name: 'Main About 1 Page', file: 'main-about-1-page.liquid' },
    'main-about-2-page': { category: 'content', name: 'Main About 2 Page', file: 'main-about-2-page.liquid' },
    'main-account': { category: 'content', name: 'Main Account', file: 'main-account.liquid' },
    'main-activate_account': { category: 'content', name: 'Main Activate_account', file: 'main-activate_account.liquid' },
    'main-addresses': { category: 'content', name: 'Main Addresses', file: 'main-addresses.liquid' },
    'main-article-with-product': { category: 'product', name: 'Main Article With Product', file: 'main-article-with-product.liquid' },
    'main-article': { category: 'content', name: 'Main Article', file: 'main-article.liquid' },
    'main-blog-full-width': { category: 'content', name: 'Main Blog Full Width', file: 'main-blog-full-width.liquid' },
    'main-blog-list': { category: 'content', name: 'Main Blog List', file: 'main-blog-list.liquid' },
    'main-blog-masonry': { category: 'content', name: 'Main Blog Masonry', file: 'main-blog-masonry.liquid' },
    'main-blog-simple': { category: 'content', name: 'Main Blog Simple', file: 'main-blog-simple.liquid' },
    'main-blog': { category: 'content', name: 'Main Blog', file: 'main-blog.liquid' },
    'main-brands-page': { category: 'brand', name: 'Main Brands Page', file: 'main-brands-page.liquid' },
    'main-cart': { category: 'content', name: 'Main Cart', file: 'main-cart.liquid' },
    'main-collection-banner-adv': { category: 'collection', name: 'Main Collection Banner Adv', file: 'main-collection-banner-adv.liquid' },
    'main-collection-banner': { category: 'collection', name: 'Main Collection Banner', file: 'main-collection-banner.liquid' },
    'main-collection-express-order': { category: 'collection', name: 'Main Collection Express Order', file: 'main-collection-express-order.liquid' },
    'main-collection-full-width': { category: 'collection', name: 'Main Collection Full Width', file: 'main-collection-full-width.liquid' },
    'main-collection-masonry': { category: 'collection', name: 'Main Collection Masonry', file: 'main-collection-masonry.liquid' },
    'main-collection-product-grid': { category: 'product', name: 'Main Collection Product Grid', file: 'main-collection-product-grid.liquid' },
    'main-collection-right-sidebar': { category: 'collection', name: 'Main Collection Right Sidebar', file: 'main-collection-right-sidebar.liquid' },
    'main-contact-us-1': { category: 'content', name: 'Main Contact Us 1', file: 'main-contact-us-1.liquid' },
    'main-contact-us-2': { category: 'content', name: 'Main Contact Us 2', file: 'main-contact-us-2.liquid' },
    'main-faqs-page': { category: 'faq', name: 'Main Faqs Page', file: 'main-faqs-page.liquid' },
    'main-list-collections': { category: 'collection', name: 'Main List Collections', file: 'main-list-collections.liquid' },
    'main-login': { category: 'content', name: 'Main Login', file: 'main-login.liquid' },
    'main-lookbook-page': { category: 'content', name: 'Main Lookbook Page', file: 'main-lookbook-page.liquid' },
    'main-order': { category: 'content', name: 'Main Order', file: 'main-order.liquid' },
    'main-page': { category: 'content', name: 'Main Page', file: 'main-page.liquid' },
    'main-portfolio-1-page': { category: 'content', name: 'Main Portfolio 1 Page', file: 'main-portfolio-1-page.liquid' },
    'main-portfolio-2-page': { category: 'content', name: 'Main Portfolio 2 Page', file: 'main-portfolio-2-page.liquid' },
    'main-product-full-width-2': { category: 'product', name: 'Main Product Full Width 2', file: 'main-product-full-width-2.liquid' },
    'main-product-full-width': { category: 'product', name: 'Main Product Full Width', file: 'main-product-full-width.liquid' },
    'main-product-gallery': { category: 'product', name: 'Main Product Gallery', file: 'main-product-gallery.liquid' },
    'main-product-horizontal-tabs-no-sidebar': { category: 'product', name: 'Main Product Horizontal Tabs No Sidebar', file: 'main-product-horizontal-tabs-no-sidebar.liquid' },
    'main-product-left-right-sidebar': { category: 'product', name: 'Main Product Left Right Sidebar', file: 'main-product-left-right-sidebar.liquid' },
    'main-product-left-thumbs': { category: 'product', name: 'Main Product Left Thumbs', file: 'main-product-left-thumbs.liquid' },
    'main-product-right-thumbs': { category: 'product', name: 'Main Product Right Thumbs', file: 'main-product-right-thumbs.liquid' },
    'main-product-step-by-step': { category: 'product', name: 'Main Product Step By Step', file: 'main-product-step-by-step.liquid' },
    'main-product': { category: 'product', name: 'Main Product', file: 'main-product.liquid' },
    'main-register': { category: 'content', name: 'Main Register', file: 'main-register.liquid' },
    'main-reset_password': { category: 'content', name: 'Main Reset_password', file: 'main-reset_password.liquid' },
    'main-search': { category: 'content', name: 'Main Search', file: 'main-search.liquid' },
    'main-sub-collection-1-page': { category: 'collection', name: 'Main Sub Collection 1 Page', file: 'main-sub-collection-1-page.liquid' },
    'main-wishlist-page': { category: 'content', name: 'Main Wishlist Page', file: 'main-wishlist-page.liquid' },
    'marquee': { category: 'banner', name: 'Marquee', file: 'marquee.liquid' },
    'multilayer-image': { category: 'content', name: 'Multilayer Image', file: 'multilayer-image.liquid' },
    'newsletter-with-banner-collapsible': { category: 'hero', name: 'Newsletter With Banner Collapsible', file: 'newsletter-with-banner-collapsible.liquid' },
    'newsletter-with-countdown': { category: 'newsletter', name: 'Newsletter With Countdown', file: 'newsletter-with-countdown.liquid' },
    'newsletter': { category: 'newsletter', name: 'Newsletter', file: 'newsletter.liquid' },
    'page': { category: 'content', name: 'Page', file: 'page.liquid' },
    'password-page-1': { category: 'content', name: 'Password Page 1', file: 'password-page-1.liquid' },
    'password-page-2': { category: 'content', name: 'Password Page 2', file: 'password-page-2.liquid' },
    'pickup-availability': { category: 'content', name: 'Pickup Availability', file: 'pickup-availability.liquid' },
    'policies-block': { category: 'faq', name: 'Policies Block', file: 'policies-block.liquid' },
    'predictive-search': { category: 'content', name: 'Predictive Search', file: 'predictive-search.liquid' },
    'product-block-02': { category: 'product', name: 'Product Block 02', file: 'product-block-02.liquid' },
    'product-block-vertical': { category: 'product', name: 'Product Block Vertical', file: 'product-block-vertical.liquid' },
    'product-block': { category: 'product', name: 'Product Block', file: 'product-block.liquid' },
    'product-recently-viewed': { category: 'product', name: 'Product Recently Viewed', file: 'product-recently-viewed.liquid' },
    'product-recommendations': { category: 'product', name: 'Product Recommendations', file: 'product-recommendations.liquid' },
    'product-tab-block': { category: 'product', name: 'Product Tab Block', file: 'product-tab-block.liquid' },
    'promo-banner-with-product-grid': { category: 'product', name: 'Promo Banner With Product Grid', file: 'promo-banner-with-product-grid.liquid' },
    'puzzled-image-banner': { category: 'hero', name: 'Puzzled Image Banner', file: 'puzzled-image-banner.liquid' },
    'quick-order-list': { category: 'content', name: 'Quick Order List', file: 'quick-order-list.liquid' },
    'rich-text': { category: 'content', name: 'Rich Text', file: 'rich-text.liquid' },
    'search-block': { category: 'content', name: 'Search Block', file: 'search-block.liquid' },
    'slidable-spotlight': { category: 'banner', name: 'Slidable Spotlight', file: 'slidable-spotlight.liquid' },
    'slide-show': { category: 'hero', name: 'Slide Show', file: 'slide-show.liquid' },
    'special-banner': { category: 'hero', name: 'Special Banner', file: 'special-banner.liquid' },
    'spotlight-block': { category: 'banner', name: 'Spotlight Block', file: 'spotlight-block.liquid' },
    'spotlight-products': { category: 'product', name: 'Spotlight Products', file: 'spotlight-products.liquid' },
    'sticky-scrolling-banner': { category: 'hero', name: 'Sticky Scrolling Banner', file: 'sticky-scrolling-banner.liquid' },
    'store-locator': { category: 'content', name: 'Store Locator', file: 'store-locator.liquid' },
    'tiktok-embedder': { category: 'social', name: 'Tiktok Embedder', file: 'tiktok-embedder.liquid' },
    'video-block': { category: 'video', name: 'Video Block', file: 'video-block.liquid' },
    'video-carousel': { category: 'video', name: 'Video Carousel', file: 'video-carousel.liquid' },
};
