-- ConvertFlow AI - Complete Section Library (100 Premium Sections) - MySQL Compatible
-- Run this after Prisma db push to seed the sections table

-- ============================================
-- CATEGORY 1: HERO SECTIONS (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Split Hero with Video Background', 'Hero Sections', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Transform Your Business Today", "description": "Join thousands of successful merchants", "buttonText": "Get Started", "primaryColor": "#667eea", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 120, "paddingBottom": 120, "alignment": "center"}}', true),
('Parallax Hero with Countdown', 'Hero Sections', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Limited Time Offer", "description": "Sale ends soon - don''t miss out!", "buttonText": "Shop Sale", "primaryColor": "#e53e3e", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)", "headingFont": {"family": "Montserrat", "weight": 800}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 140, "paddingBottom": 140, "alignment": "center"}}', true),
('Minimal Split Layout', 'Hero Sections', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Elegance Simplified", "description": "Where minimalism meets luxury", "buttonText": "Explore", "primaryColor": "#000000", "textColor": "#1a202c", "backgroundColor": "#f7fafc", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lato", "weight": 400}, "paddingTop": 100, "paddingBottom": 100, "alignment": "left"}}', true),
('Full Screen Video Hero', 'Hero Sections', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Experience the Difference", "description": "Premium quality at your fingertips", "buttonText": "Watch Video", "primaryColor": "#ffffff", "textColor": "#ffffff", "backgroundColor": "rgba(0, 0, 0, 0.5)", "headingFont": {"family": "Roboto", "weight": 900}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 160, "paddingBottom": 160, "alignment": "center"}}', true),
('Image Carousel Hero', 'Hero Sections', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Discover Our Collection", "description": "Curated styles for every occasion", "buttonText": "Browse All", "primaryColor": "#48bb78", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)", "headingFont": {"family": "Bebas Neue", "weight": 400}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 100, "paddingBottom": 100, "alignment": "center"}}', true),
('Animated Text Hero', 'Hero Sections', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Innovation Starts Here", "description": "Revolutionary products, unbeatable prices", "buttonText": "Learn More", "primaryColor": "#805ad5", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Poppins", "weight": 800}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 90, "paddingBottom": 90, "alignment": "center"}}', true),
('Split Hero with Form', 'Hero Sections', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Get 20% Off Your First Order", "description": "Sign up now for exclusive deals", "buttonText": "Claim Discount", "primaryColor": "#dd6b20", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #fc4a1a 0%, #f7b733 100%)", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 110, "paddingBottom": 110, "alignment": "left"}}', true),
('Multi-CTA Hero', 'Hero Sections', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Your Success, Our Mission", "description": "Tools to grow your business", "buttonText": "Start Free Trial", "primaryColor": "#3182ce", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 120, "paddingBottom": 120, "alignment": "center"}}', true),
('Product Showcase Hero', 'Hero Sections', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "New Arrival: Premium Collection", "description": "Limited edition pieces now available", "buttonText": "Shop Now", "primaryColor": "#d69e2e", "textColor": "#1a202c", "backgroundColor": "#fffaf0", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lora", "weight": 400}, "paddingTop": 100, "paddingBottom": 100, "alignment": "center"}}', true),
('Gradient Overlay Hero', 'Hero Sections', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Bold. Beautiful. Yours.", "description": "Redefining modern commerce", "buttonText": "Discover More", "primaryColor": "#f687b3", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)", "headingFont": {"family": "Righteous", "weight": 400}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 130, "paddingBottom": 130, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 2: ANNOUNCEMENT BARS (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Scrolling Ticker Bar', 'Announcement Bars', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "🎉 Flash Sale: 50% OFF Everything - Limited Time Only!", "backgroundColor": "linear-gradient(90deg, #ff6b6b 0%, #ee5a6f 100%)", "textColor": "#ffffff", "headingFont": {"family": "Inter", "weight": 600}, "paddingTop": 12, "paddingBottom": 12, "alignment": "center"}}', true),
('Countdown Timer Bar', 'Announcement Bars', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "⏰ Sale Ends In: 23:59:45", "backgroundColor": "#000000", "textColor": "#ffffff", "primaryColor": "#ffd700", "headingFont": {"family": "Roboto", "weight": 700}, "paddingTop": 14, "paddingBottom": 14, "alignment": "center"}}', true),
('Free Shipping Banner', 'Announcement Bars', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "🚚 Free Shipping on Orders Over $50", "backgroundColor": "#4facfe", "textColor": "#ffffff", "headingFont": {"family": "Poppins", "weight": 500}, "paddingTop": 10, "paddingBottom": 10, "alignment": "center"}}', true),
('Multi-Message Rotator', 'Announcement Bars', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "New Arrivals Weekly | Free Returns | 24/7 Support", "backgroundColor": "linear-gradient(90deg, #667eea 0%, #764ba2 100%)", "textColor": "#ffffff", "headingFont": {"family": "Inter", "weight": 500}, "paddingTop": 12, "paddingBottom": 12, "alignment": "center"}}', true),
('Urgency Alert Bar', 'Announcement Bars', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "🔥 Only 5 Items Left in Stock - Order Now!", "backgroundColor": "#fed7d7", "textColor": "#c53030", "primaryColor": "#e53e3e", "headingFont": {"family": "Montserrat", "weight": 700}, "paddingTop": 16, "paddingBottom": 16, "alignment": "center"}}', true),
('Holiday Sale Bar', 'Announcement Bars', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "🎄 Holiday Special: Buy 2 Get 1 Free", "backgroundColor": "#c53030", "textColor": "#ffffff", "headingFont": {"family": "Bebas Neue", "weight": 400}, "paddingTop": 14, "paddingBottom": 14, "alignment": "center"}}', true),
('Newsletter Signup Bar', 'Announcement Bars', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "💌 Join Our VIP List - Get 15% Off Your First Order", "backgroundColor": "#805ad5", "textColor": "#ffffff", "headingFont": {"family": "Poppins", "weight": 600}, "paddingTop": 12, "paddingBottom": 12, "alignment": "center"}}', true),
('Product Launch Bar', 'Announcement Bars', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "✨ New Collection Just Dropped - Shop Now", "backgroundColor": "#000000", "textColor": "#ffffff", "primaryColor": "#48bb78", "headingFont": {"family": "Montserrat", "weight": 600}, "paddingTop": 14, "paddingBottom": 14, "alignment": "center"}}', true),
('Trust Badge Bar', 'Announcement Bars', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "⭐ Rated 4.9/5 by 10,000+ Happy Customers", "backgroundColor": "#f7fafc", "textColor": "#1a202c", "headingFont": {"family": "Inter", "weight": 500}, "paddingTop": 12, "paddingBottom": 12, "alignment": "center"}}', true),
('Seasonal Promo Bar', 'Announcement Bars', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "🌸 Spring Sale: Up to 40% Off Sitewide", "backgroundColor": "linear-gradient(90deg, #f093fb 0%, #f5576c 100%)", "textColor": "#ffffff", "headingFont": {"family": "Righteous", "weight": 400}, "paddingTop": 16, "paddingBottom": 16, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 3: HEADER & NAVIGATION (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Transparent Overlay Header', 'Header & Sticky Navigation', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "transparent", "textColor": "#ffffff", "primaryColor": "#667eea", "headingFont": {"family": "Inter", "weight": 600}, "paddingTop": 20, "paddingBottom": 20}}', true),
('Mega Menu Navigation', 'Header & Sticky Navigation', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#ffffff", "textColor": "#1a202c", "primaryColor": "#000000", "headingFont": {"family": "Montserrat", "weight": 600}, "paddingTop": 24, "paddingBottom": 24}}', true),
('Sticky Header with Search', 'Header & Sticky Navigation', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#f7fafc", "textColor": "#1a202c", "primaryColor": "#3182ce", "headingFont": {"family": "Poppins", "weight": 600}, "paddingTop": 16, "paddingBottom": 16}}', true),
('Minimal Header', 'Header & Sticky Navigation', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#ffffff", "textColor": "#1a202c", "primaryColor": "#000000", "headingFont": {"family": "Inter", "weight": 500}, "paddingTop": 20, "paddingBottom": 20}}', true),
('Header with Top Bar', 'Header & Sticky Navigation', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#1a202c", "textColor": "#ffffff", "primaryColor": "#48bb78", "headingFont": {"family": "Roboto", "weight": 600}, "paddingTop": 8, "paddingBottom": 8}}', true),
('Centered Logo Header', 'Header & Sticky Navigation', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#ffffff", "textColor": "#1a202c", "primaryColor": "#667eea", "headingFont": {"family": "Playfair Display", "weight": 700}, "paddingTop": 28, "paddingBottom": 28}}', true),
('Header with Icons', 'Header & Sticky Navigation', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#f7fafc", "textColor": "#1a202c", "primaryColor": "#805ad5", "headingFont": {"family": "Inter", "weight": 600}, "paddingTop": 18, "paddingBottom": 18}}', true),
('Gradient Header', 'Header & Sticky Navigation', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "linear-gradient(90deg, #667eea 0%, #764ba2 100%)", "textColor": "#ffffff", "primaryColor": "#ffffff", "headingFont": {"family": "Montserrat", "weight": 700}, "paddingTop": 20, "paddingBottom": 20}}', true),
('Split Navigation Header', 'Header & Sticky Navigation', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#ffffff", "textColor": "#1a202c", "primaryColor": "#dd6b20", "headingFont": {"family": "Poppins", "weight": 600}, "paddingTop": 22, "paddingBottom": 22}}', true),
('Mobile-First Header', 'Header & Sticky Navigation', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"backgroundColor": "#000000", "textColor": "#ffffff", "primaryColor": "#48bb78", "headingFont": {"family": "Bebas Neue", "weight": 400}, "paddingTop": 16, "paddingBottom": 16}}', true);

-- ============================================
-- CATEGORY 4: PRODUCT & INFO PAGES (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Product Grid Showcase', 'Product & Info Pages', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Featured Products", "description": "Our best sellers", "buttonText": "Shop Now", "primaryColor": "#667eea", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Product Comparison Table', 'Product & Info Pages', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Compare Products", "description": "Find your perfect match", "buttonText": "View Details", "primaryColor": "#3182ce", "textColor": "#1a202c", "backgroundColor": "#f7fafc", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Product Quick View', 'Product & Info Pages', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Quick Shop", "description": "Preview without leaving the page", "buttonText": "Add to Cart", "primaryColor": "#48bb78", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Montserrat", "weight": 600}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Product Video Gallery', 'Product & Info Pages', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "See It In Action", "description": "Watch product demos", "buttonText": "Play Video", "primaryColor": "#e53e3e", "textColor": "#ffffff", "backgroundColor": "#1a202c", "headingFont": {"family": "Roboto", "weight": 700}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Product Bundle Builder', 'Product & Info Pages', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Build Your Bundle", "description": "Mix and match to save more", "buttonText": "Create Bundle", "primaryColor": "#805ad5", "textColor": "#1a202c", "backgroundColor": "#faf5ff", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Size Guide Section', 'Product & Info Pages', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Find Your Perfect Fit", "description": "Use our interactive size guide", "buttonText": "Check Size", "primaryColor": "#dd6b20", "textColor": "#1a202c", "backgroundColor": "#fffaf0", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lato", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Product Tabs Layout', 'Product & Info Pages', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Product Details", "description": "Everything you need to know", "buttonText": "Read More", "primaryColor": "#000000", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Inter", "weight": 600}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "left"}}', true),
('Product Carousel', 'Product & Info Pages', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "You May Also Like", "description": "Recommended products", "buttonText": "View All", "primaryColor": "#d69e2e", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Product Story Section', 'Product & Info Pages', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "The Story Behind", "description": "Crafted with care and passion", "buttonText": "Learn More", "primaryColor": "#2d3748", "textColor": "#1a202c", "backgroundColor": "#edf2f7", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lora", "weight": 400}, "paddingTop": 100, "paddingBottom": 100, "alignment": "center"}}', true),
('Product Reviews Showcase', 'Product & Info Pages', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "What Customers Say", "description": "Real reviews from real people", "buttonText": "Write a Review", "primaryColor": "#48bb78", "textColor": "#1a202c", "backgroundColor": "#f0fff4", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 5: URGENCY TOOLS (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Flash Sale Countdown', 'Urgency Tools', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Flash Sale Ends Soon!", "description": "Grab these deals before they''re gone", "buttonText": "Shop Now", "primaryColor": "#e53e3e", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #e53e3e 0%, #c53030 100%)", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 40, "paddingBottom": 40, "alignment": "center"}}', true),
('Stock Level Indicator', 'Urgency Tools', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Selling Fast!", "description": "Only a few left in stock", "buttonText": "Claim Yours", "primaryColor": "#dd6b20", "textColor": "#1a202c", "backgroundColor": "#fffaf0", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 30, "paddingBottom": 30, "alignment": "center"}}', true),
('Live Visitor Counter', 'Urgency Tools', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "23 People Viewing This!", "description": "High demand right now", "buttonText": "Add to Cart", "primaryColor": "#e53e3e", "textColor": "#ffffff", "backgroundColor": "#1a202c", "headingFont": {"family": "Roboto", "weight": 700}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 20, "paddingBottom": 20, "alignment": "center"}}', true),
('Recent Purchase Popup', 'Urgency Tools', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Someone just purchased!", "description": "Sarah from NY bought this 2 min ago", "primaryColor": "#48bb78", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Inter", "weight": 600}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 16, "paddingBottom": 16, "alignment": "left"}}', true),
('Expiring Discount Timer', 'Urgency Tools', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Your Discount Expires In:", "description": "Use code SAVE20 at checkout", "buttonText": "Apply Code", "primaryColor": "#805ad5", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #805ad5 0%, #553c9a 100%)", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 40, "paddingBottom": 40, "alignment": "center"}}', true),
('Cart Abandonment Saver', 'Urgency Tools', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Wait! Don''t Leave Yet", "description": "Complete your purchase and save 10%", "buttonText": "Complete Order", "primaryColor": "#3182ce", "textColor": "#ffffff", "backgroundColor": "#ebf8ff", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 40, "paddingBottom": 40, "alignment": "center"}}', true),
('Shipping Deadline Alert', 'Urgency Tools', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Order in next 2h 45m", "description": "For guaranteed next-day delivery", "buttonText": "Order Now", "primaryColor": "#d69e2e", "textColor": "#1a202c", "backgroundColor": "#fffff0", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 30, "paddingBottom": 30, "alignment": "center"}}', true),
('Limited Edition Badge', 'Urgency Tools', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Limited Edition", "description": "Only 50 pieces ever made", "buttonText": "Reserve Yours", "primaryColor": "#d69e2e", "textColor": "#ffffff", "backgroundColor": "#000000", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lora", "weight": 400}, "paddingTop": 50, "paddingBottom": 50, "alignment": "center"}}', true),
('Social Proof Ticker', 'Urgency Tools', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "1,247 sold in last 24 hours", "description": "Trending product", "primaryColor": "#e53e3e", "textColor": "#1a202c", "backgroundColor": "#fff5f5", "headingFont": {"family": "Roboto", "weight": 700}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 20, "paddingBottom": 20, "alignment": "center"}}', true),
('Price Increase Warning', 'Urgency Tools', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Price Going Up Tomorrow!", "description": "Lock in today''s price now", "buttonText": "Buy at Current Price", "primaryColor": "#c53030", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #fc4a1a 0%, #f7b733 100%)", "headingFont": {"family": "Montserrat", "weight": 800}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 40, "paddingBottom": 40, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 6: RETENTION TOOLS (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Exit Intent Popup', 'Retention Tools', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Wait! Get 15% Off", "description": "Subscribe before you go", "buttonText": "Claim Discount", "primaryColor": "#667eea", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Email Capture Banner', 'Retention Tools', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Join Our Newsletter", "description": "Get exclusive deals and updates", "buttonText": "Subscribe", "primaryColor": "#3182ce", "textColor": "#ffffff", "backgroundColor": "#ebf8ff", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Loyalty Points Widget', 'Retention Tools', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Earn Rewards Points", "description": "Every purchase earns you points", "buttonText": "Join Program", "primaryColor": "#d69e2e", "textColor": "#1a202c", "backgroundColor": "#fffff0", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Spin the Wheel Popup', 'Retention Tools', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Spin to Win!", "description": "Try your luck for a special discount", "buttonText": "Spin Now", "primaryColor": "#e53e3e", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)", "headingFont": {"family": "Bebas Neue", "weight": 400}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Referral Program Banner', 'Retention Tools', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Refer a Friend, Get $20", "description": "Share your unique referral link", "buttonText": "Start Referring", "primaryColor": "#48bb78", "textColor": "#ffffff", "backgroundColor": "#f0fff4", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Back in Stock Alert', 'Retention Tools', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Get Notified When Available", "description": "Be the first to know when this item restocks", "buttonText": "Notify Me", "primaryColor": "#805ad5", "textColor": "#1a202c", "backgroundColor": "#faf5ff", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 40, "paddingBottom": 40, "alignment": "center"}}', true),
('Wishlist Reminder', 'Retention Tools', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Items in Your Wishlist", "description": "Don''t forget about these picks", "buttonText": "View Wishlist", "primaryColor": "#dd6b20", "textColor": "#1a202c", "backgroundColor": "#fffaf0", "headingFont": {"family": "Montserrat", "weight": 600}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('SMS Signup Widget', 'Retention Tools', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Get Texts, Get Deals", "description": "Join our SMS list for flash sale alerts", "buttonText": "Sign Up", "primaryColor": "#3182ce", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Birthday Discount Widget', 'Retention Tools', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "🎂 Birthday Treat Awaits!", "description": "Tell us your birthday for a special surprise", "buttonText": "Set Birthday", "primaryColor": "#ec4899", "textColor": "#ffffff", "backgroundColor": "#fdf2f8", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('VIP Club Invitation', 'Retention Tools', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Join Our VIP Club", "description": "Exclusive perks for our best customers", "buttonText": "Become VIP", "primaryColor": "#d69e2e", "textColor": "#ffffff", "backgroundColor": "#000000", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lora", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 7: TRUST BADGES (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Security Badges Strip', 'Trust Badges', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Shop with Confidence", "description": "100% Secure Checkout", "primaryColor": "#48bb78", "textColor": "#1a202c", "backgroundColor": "#f7fafc", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Money Back Guarantee', 'Trust Badges', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "30-Day Money Back Guarantee", "description": "No questions asked returns", "primaryColor": "#3182ce", "textColor": "#1a202c", "backgroundColor": "#ebf8ff", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Customer Reviews Summary', 'Trust Badges', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Trusted by 50,000+ Customers", "description": "4.9 out of 5 star rating", "primaryColor": "#d69e2e", "textColor": "#1a202c", "backgroundColor": "#fffff0", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Shipping & Returns Info', 'Trust Badges', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Free Shipping & Easy Returns", "description": "Free shipping over $50, 30-day returns", "primaryColor": "#667eea", "textColor": "#1a202c", "backgroundColor": "#f7fafc", "headingFont": {"family": "Inter", "weight": 600}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 50, "paddingBottom": 50, "alignment": "center"}}', true),
('Payment Methods Display', 'Trust Badges', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Secure Payment Options", "description": "We accept all major payment methods", "primaryColor": "#2d3748", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Roboto", "weight": 600}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 40, "paddingBottom": 40, "alignment": "center"}}', true),
('Certification Badges', 'Trust Badges', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Certified & Verified", "description": "Industry-leading certifications", "primaryColor": "#48bb78", "textColor": "#ffffff", "backgroundColor": "#1a202c", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Social Proof Counter', 'Trust Badges', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Join Our Growing Community", "description": "100K+ Instagram followers", "primaryColor": "#805ad5", "textColor": "#1a202c", "backgroundColor": "#faf5ff", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Award Badges Section', 'Trust Badges', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Award-Winning Products", "description": "Recognized by industry experts", "primaryColor": "#d69e2e", "textColor": "#1a202c", "backgroundColor": "#fffaf0", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lora", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('FAQ Trust Section', 'Trust Badges', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Frequently Asked Questions", "description": "Find answers to common questions", "primaryColor": "#3182ce", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Eco-Friendly Badge', 'Trust Badges', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Sustainability Committed", "description": "Carbon neutral shipping, eco packaging", "primaryColor": "#38a169", "textColor": "#ffffff", "backgroundColor": "#f0fff4", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 8: FOOTER SECTIONS (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Multi-Column Footer', 'Footer Sections', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Stay Connected", "description": "Follow us on social media", "primaryColor": "#1a202c", "textColor": "#ffffff", "backgroundColor": "#1a202c", "headingFont": {"family": "Montserrat", "weight": 600}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "left"}}', true),
('Minimal Footer', 'Footer Sections', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "ConvertFlow AI", "description": "© 2025 All rights reserved", "primaryColor": "#000000", "textColor": "#718096", "backgroundColor": "#ffffff", "headingFont": {"family": "Inter", "weight": 600}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 40, "paddingBottom": 40, "alignment": "center"}}', true),
('Newsletter Footer', 'Footer Sections', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Subscribe to Our Newsletter", "description": "Be the first to know about new products", "buttonText": "Subscribe", "primaryColor": "#667eea", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #1a202c 0%, #2d3748 100%)", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Social Media Footer', 'Footer Sections', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Follow Us", "description": "Stay updated on all platforms", "primaryColor": "#805ad5", "textColor": "#ffffff", "backgroundColor": "#000000", "headingFont": {"family": "Bebas Neue", "weight": 400}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Contact Info Footer', 'Footer Sections', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Get in Touch", "description": "We''re here to help", "primaryColor": "#3182ce", "textColor": "#1a202c", "backgroundColor": "#f7fafc", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "left"}}', true),
('Map Footer', 'Footer Sections', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Visit Our Store", "description": "Find us at our physical location", "primaryColor": "#48bb78", "textColor": "#ffffff", "backgroundColor": "#1a202c", "headingFont": {"family": "Montserrat", "weight": 600}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Mega Footer', 'Footer Sections', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Everything You Need", "description": "Explore our complete ecosystem", "primaryColor": "#667eea", "textColor": "#e2e8f0", "backgroundColor": "#0f172a", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 100, "paddingBottom": 80, "alignment": "left"}}', true),
('App Download Footer', 'Footer Sections', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Download Our App", "description": "Shop on the go with our mobile app", "buttonText": "Get the App", "primaryColor": "#000000", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Stacked Footer', 'Footer Sections', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Quick Links", "description": "Navigate easily", "primaryColor": "#2d3748", "textColor": "#a0aec0", "backgroundColor": "#1a202c", "headingFont": {"family": "Roboto", "weight": 600}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 80, "paddingBottom": 40, "alignment": "center"}}', true),
('Brand Story Footer', 'Footer Sections', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Our Story", "description": "Founded with a passion for quality", "primaryColor": "#d69e2e", "textColor": "#ffffff", "backgroundColor": "#000000", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lora", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 9: CUSTOM CTAs (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Full Width CTA Banner', 'Custom CTAs', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Ready to Transform?", "description": "Start your journey today", "buttonText": "Get Started Free", "primaryColor": "#3182ce", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)", "headingFont": {"family": "Poppins", "weight": 800}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 100, "paddingBottom": 100, "alignment": "center"}}', true),
('Split CTA with Image', 'Custom CTAs', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Experience Premium Quality", "description": "See why thousands choose us", "buttonText": "Shop Collection", "primaryColor": "#667eea", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lato", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "left"}}', true),
('Floating CTA Bar', 'Custom CTAs', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Limited Offer!", "description": "Use code SAVE20", "buttonText": "Apply Now", "primaryColor": "#e53e3e", "textColor": "#ffffff", "backgroundColor": "#1a202c", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 16, "paddingBottom": 16, "alignment": "center"}}', true),
('Dual Button CTA', 'Custom CTAs', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Choose Your Path", "description": "Free trial or premium plan", "buttonText": "Start Free", "primaryColor": "#805ad5", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #805ad5 0%, #553c9a 100%)", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Video Background CTA', 'Custom CTAs', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "See It In Action", "description": "Watch how it works", "buttonText": "Play Demo", "primaryColor": "#ffffff", "textColor": "#ffffff", "backgroundColor": "rgba(0, 0, 0, 0.7)", "headingFont": {"family": "Roboto", "weight": 900}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 120, "paddingBottom": 120, "alignment": "center"}}', true),
('Countdown CTA', 'Custom CTAs', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Sale Ends at Midnight!", "description": "Don''t miss these incredible savings", "buttonText": "Shop the Sale", "primaryColor": "#dd6b20", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #fc4a1a 0%, #f7b733 100%)", "headingFont": {"family": "Bebas Neue", "weight": 400}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Testimonial CTA', 'Custom CTAs', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Join 10,000+ Happy Customers", "description": "See why they love us", "buttonText": "Read Reviews", "primaryColor": "#48bb78", "textColor": "#1a202c", "backgroundColor": "#f0fff4", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Pricing CTA', 'Custom CTAs', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Simple, Transparent Pricing", "description": "No hidden fees, cancel anytime", "buttonText": "View Plans", "primaryColor": "#3182ce", "textColor": "#1a202c", "backgroundColor": "#ebf8ff", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('App Install CTA', 'Custom CTAs', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Get Our Mobile App", "description": "Shop faster on mobile", "buttonText": "Download Free", "primaryColor": "#000000", "textColor": "#ffffff", "backgroundColor": "#000000", "headingFont": {"family": "Montserrat", "weight": 800}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Animated CTA Banner', 'Custom CTAs', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Your Store, Supercharged", "description": "Add sections that convert visitors into customers", "buttonText": "Explore Sections", "primaryColor": "#f687b3", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)", "headingFont": {"family": "Righteous", "weight": 400}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 100, "paddingBottom": 100, "alignment": "center"}}', true);

-- ============================================
-- CATEGORY 10: SPECIAL SECTIONS (10 variations)
-- ============================================

INSERT INTO sections (name, category, variation_number, liquid_code, schema_json, is_premium) VALUES
('Testimonial Carousel', 'Special Sections', 1, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "What Our Customers Say", "description": "Real stories from real people", "primaryColor": "#667eea", "textColor": "#1a202c", "backgroundColor": "#f7fafc", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Instagram Feed Grid', 'Special Sections', 2, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Follow Us @store", "description": "See our latest posts", "primaryColor": "#e1306c", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Blog Post Showcase', 'Special Sections', 3, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "From Our Blog", "description": "Tips, trends, and inspiration", "buttonText": "Read More", "primaryColor": "#3182ce", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Playfair Display", "weight": 700}, "bodyFont": {"family": "Lora", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Team Introduction', 'Special Sections', 4, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Meet Our Team", "description": "The people behind the brand", "primaryColor": "#805ad5", "textColor": "#1a202c", "backgroundColor": "#faf5ff", "headingFont": {"family": "Montserrat", "weight": 700}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Brand Partners Logo Grid', 'Special Sections', 5, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Trusted By Leading Brands", "description": "Partners who believe in us", "primaryColor": "#2d3748", "textColor": "#718096", "backgroundColor": "#f7fafc", "headingFont": {"family": "Inter", "weight": 600}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Timeline / Story Section', 'Special Sections', 6, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Our Journey", "description": "From humble beginnings to today", "primaryColor": "#48bb78", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Stats / Numbers Section', 'Special Sections', 7, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "By the Numbers", "description": "Our impact in numbers", "primaryColor": "#667eea", "textColor": "#ffffff", "backgroundColor": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", "headingFont": {"family": "Montserrat", "weight": 800}, "bodyFont": {"family": "Open Sans", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Contact Form Section', 'Special Sections', 8, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Get in Touch", "description": "We''d love to hear from you", "buttonText": "Send Message", "primaryColor": "#3182ce", "textColor": "#1a202c", "backgroundColor": "#ebf8ff", "headingFont": {"family": "Inter", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true),
('Image Gallery Masonry', 'Special Sections', 9, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Gallery", "description": "Browse our curated collection", "primaryColor": "#000000", "textColor": "#1a202c", "backgroundColor": "#ffffff", "headingFont": {"family": "Bebas Neue", "weight": 400}, "bodyFont": {"family": "Roboto", "weight": 400}, "paddingTop": 60, "paddingBottom": 60, "alignment": "center"}}', true),
('Video Testimonials Grid', 'Special Sections', 10, '{% comment %}Liquid template{% endcomment %}', '{"settings": {"heading": "Hear From Our Customers", "description": "Video reviews and testimonials", "buttonText": "Watch All", "primaryColor": "#e53e3e", "textColor": "#ffffff", "backgroundColor": "#1a202c", "headingFont": {"family": "Poppins", "weight": 700}, "bodyFont": {"family": "Inter", "weight": 400}, "paddingTop": 80, "paddingBottom": 80, "alignment": "center"}}', true);

-- Verify counts
SELECT category, COUNT(*) as section_count FROM sections GROUP BY category ORDER BY category;
