import React, { useEffect, useState } from 'react';
import { json, redirect } from "@remix-run/node";
import { useLoaderData, useNavigate, useFetcher } from "@remix-run/react";
import { authenticate } from "../shopify.server";
import { db } from "../db.server";
import { useVisualBuilderStore } from '../store/visualBuilderStore';
import { readTemplateFile, installTemplateToTheme, publishLiquidToTheme } from '../utils/templateInstaller.server';

import EditorToolbar from '../components/visual-builder/EditorToolbar';
import EditorSidebar from '../components/visual-builder/EditorSidebar';
import EditorCanvas from '../components/visual-builder/EditorCanvas';
import EditorProperties from '../components/visual-builder/EditorProperties';

// Load Inter from CDN
export const links = () => [
    { rel: "preconnect", href: "https://fonts.googleapis.com" },
    { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" },
    { rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" },
];

export const loader = async ({ request, params }) => {
    const { session, admin } = await authenticate.admin(request);
    const shop = session.shop;
    const pageId = params.pageId;

    if (!pageId) return redirect('/app/visual-builder');

    // Load the page from DB
    let page = null;
    try {
        const result = await db.query(
            'SELECT * FROM visual_pages WHERE id = ? AND shop_domain = ?',
            [pageId, shop]
        );
        page = result.rows[0] || null;
    } catch (e) {
        console.error('[Editor] Load error:', e.message);
    }

    if (!page) return redirect('/app/visual-builder');

    return json({ page, shop });
};

export const action = async ({ request, params }) => {
    const { session } = await authenticate.admin(request);
    const shop = session.shop;
    const pageId = params.pageId;
    const formData = await request.formData();
    const intent = formData.get("intent");

    if (intent === "save") {
        const elementsJson = formData.get("elements_json");
        const title = formData.get("title");

        await db.query(
            'UPDATE visual_pages SET elements_json = ?, title = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND shop_domain = ?',
            [elementsJson, title, pageId, shop]
        );

        return json({ success: true, message: 'Page saved ✓' });
    }

    if (intent === "publish") {
        const elementsJson = formData.get("elements_json");
        const title = formData.get("title");

        // Save first
        await db.query(
            'UPDATE visual_pages SET elements_json = ?, title = ?, status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND shop_domain = ?',
            [elementsJson, title, 'published', pageId, shop]
        );

        // Compile to Liquid
        let elements;
        try {
            elements = JSON.parse(elementsJson);
        } catch {
            return json({ success: false, error: 'Invalid JSON' }, { status: 400 });
        }

        const compiledHtml = compileToHtml(elements[0]);
        const compiledCss = compileToCss(elements[0]);
        const sectionName = `cf-visual-page-${pageId}`;

        const liquidContent = `
{%- comment -%} Generated by ConvertFlow Visual Builder {%- endcomment -%}
<style>
${compiledCss}
</style>
<div class="cf-visual-page" id="${sectionName}">
${compiledHtml}
</div>

{% schema %}
{
  "name": "CF Visual Page ${pageId}",
  "settings": [],
  "presets": [{ "name": "CF Visual Page ${pageId}" }]
}
{% endschema %}
        `.trim();

        try {
            await publishLiquidToTheme(shop, session.accessToken, sectionName, liquidContent);
        } catch (e) {
            console.error('[Editor] Publish error:', e.message);
            return json({ success: true, message: 'Saved but publish failed: ' + e.message });
        }

        return json({ success: true, message: 'Published to theme! ✓' });
    }

    if (intent === "install_template") {
        const templateId = formData.get("templateId");
        const templateFile = formData.get("liquidFile");

        if (!templateFile) {
            return json({ success: false, error: 'No template file specified' }, { status: 400 });
        }

        try {
            const liquidContent = readTemplateFile(templateFile);

            if (!liquidContent) {
                return json({ success: false, error: 'Template file not found' }, { status: 404 });
            }

            const result = await installTemplateToTheme(shop, session.accessToken, templateId, liquidContent);
            return json({ success: true, message: '✓ Template installed to theme!', sectionName: result.sectionName });
        } catch (e) {
            console.error('[Editor] Template install error:', e.message);
            return json({ success: false, error: 'Install failed: ' + e.message });
        }
    }

    return json({ error: "Invalid intent" }, { status: 400 });
};

// --- Simple HTML compiler ---
function compileToHtml(node) {
    if (!node) return '';
    const styles = node.settings?.styles || {};
    const styleStr = Object.entries(styles)
        .filter(([, v]) => v && v !== 'transparent')
        .map(([k, v]) => `${k.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${v}`)
        .join('; ');
    const cls = `cf-el-${node.id}`;

    switch (node.type) {
        case 'Root':
            return `<div class="${cls}" style="${styleStr}">${(node.children || []).map(compileToHtml).join('')}</div>`;
        case 'Row':
        case 'Section':
            return `<div class="${cls}" style="${styleStr}">${(node.children || []).map(compileToHtml).join('')}</div>`;
        case 'Column':
            return `<div class="${cls}" style="${styleStr}">${(node.children || []).map(compileToHtml).join('')}</div>`;
        case 'Heading':
            const tag = node.settings?.tag || 'h2';
            return `<${tag} class="${cls}" style="${styleStr}">${node.settings?.text || ''}</${tag}>`;
        case 'Paragraph':
            return `<p class="${cls}" style="${styleStr}">${node.settings?.text || ''}</p>`;
        case 'Button':
            return `<a class="${cls}" style="${styleStr}" href="${node.settings?.url || '#'}">${node.settings?.text || 'Button'}</a>`;
        case 'Image':
            return `<img class="${cls}" style="${styleStr}" src="${node.settings?.src || ''}" alt="${node.settings?.alt || ''}" loading="lazy" />`;
        case 'Spacer':
            return `<div class="${cls}" style="${styleStr}"></div>`;
        case 'Divider':
            return `<hr class="${cls}" style="${styleStr}; border: none;" />`;
        default:
            return `<div class="${cls}" style="${styleStr}">${(node.children || []).map(compileToHtml).join('')}</div>`;
    }
}

function compileToCss(node) {
    // Inline styles are used, so minimal CSS needed
    return `.cf-visual-page { font-family: Inter, system-ui, sans-serif; } .cf-visual-page img { max-width: 100%; height: auto; }`;
}

// --- Main Editor Component ---
export default function VisualBuilderEditor() {
    const { page } = useLoaderData();
    const navigate = useNavigate();
    const fetcher = useFetcher();
    const { loadPage, getElementsJSON, pageTitle, setSaving, setDirty, setPageMeta } = useVisualBuilderStore();

    // Load page data on mount
    useEffect(() => {
        if (page) {
            loadPage(page);
        }
    }, [page.id]);

    // Handle save response
    useEffect(() => {
        if (fetcher.data?.success) {
            setSaving(false);
            setDirty(false);
            if (fetcher.data.message?.includes('Published')) {
                setPageMeta({ pageStatus: 'published' });
            }
        }
    }, [fetcher.data]);

    const handleSave = () => {
        setSaving(true);
        fetcher.submit(
            {
                intent: "save",
                elements_json: getElementsJSON(),
                title: pageTitle,
            },
            { method: "POST" }
        );
    };

    const handlePublish = () => {
        setSaving(true);
        fetcher.submit(
            {
                intent: "publish",
                elements_json: getElementsJSON(),
                title: pageTitle,
            },
            { method: "POST" }
        );
    };

    const handleBack = () => {
        navigate('/app/visual-builder');
    };

    // Listen for template install events from the sidebar
    useEffect(() => {
        const handleTemplateInstall = (e) => {
            const template = e.detail;
            if (template && template.liquidFile) {
                fetcher.submit(
                    {
                        intent: "install_template",
                        templateId: template.id,
                        liquidFile: template.liquidFile,
                    },
                    { method: "POST" }
                );
            }
        };

        window.addEventListener('cf-install-template', handleTemplateInstall);
        return () => window.removeEventListener('cf-install-template', handleTemplateInstall);
    }, [fetcher]);

    // Keyboard shortcuts
    useEffect(() => {
        const handleKeyboard = (e) => {
            if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) {
                e.preventDefault();
                useVisualBuilderStore.getState().undo();
            }
            if ((e.ctrlKey || e.metaKey) && e.key === 'z' && e.shiftKey) {
                e.preventDefault();
                useVisualBuilderStore.getState().redo();
            }
            if ((e.ctrlKey || e.metaKey) && e.key === 's') {
                e.preventDefault();
                handleSave();
            }
            if (e.key === 'Delete' || e.key === 'Backspace') {
                const state = useVisualBuilderStore.getState();
                if (state.selectedId && state.selectedId !== 'root' && e.target.tagName !== 'INPUT' && e.target.tagName !== 'TEXTAREA') {
                    e.preventDefault();
                    state.removeElement(state.selectedId);
                }
            }
            if ((e.ctrlKey || e.metaKey) && e.key === 'd') {
                e.preventDefault();
                const state = useVisualBuilderStore.getState();
                if (state.selectedId) state.duplicateElement(state.selectedId);
            }
        };

        window.addEventListener('keydown', handleKeyboard);
        return () => window.removeEventListener('keydown', handleKeyboard);
    }, []);

    return (
        <div className="h-screen w-screen flex flex-col bg-surface font-sans overflow-hidden" style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>
            {/* Toolbar */}
            <EditorToolbar
                onSave={handleSave}
                onPublish={handlePublish}
                onBack={handleBack}
            />

            {/* Editor Body */}
            <div className="flex flex-1 overflow-hidden">
                <EditorSidebar />
                <EditorCanvas />
                <EditorProperties />
            </div>

            {/* Save/Install feedback toast */}
            {(fetcher.data?.message || fetcher.data?.error) && (
                <div className={`fixed bottom-6 right-6 px-4 py-3 text-white text-sm font-medium rounded-xl shadow-float animate-slide-up z-[9999] ${fetcher.data?.error ? 'bg-red-600' : 'bg-[#1a1d27]'
                    }`}>
                    {fetcher.data.message || fetcher.data.error}
                </div>
            )}
        </div>
    );
}
