/**
 * Converts a React CSS object property to a standard CSS property string.
 * Example: `backgroundColor` -> `background-color`
 */
const camelToKebab = (str) => {
    return str.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`);
};

/**
 * Extracts all styles from the JSON tree and generates a single CSS string.
 * Classes are scoped using the unique element ID (e.g., `.cf-el-root-123`).
 */
export const jsonToCss = (nodes) => {
    let cssString = '';

    const traverse = (node) => {
        if (node.settings && node.settings.styles) {
            const styles = node.settings.styles;
            const className = `cf-el-${node.id}`;

            let ruleString = `.${className} {\n`;
            for (const [key, value] of Object.entries(styles)) {
                if (value !== undefined && value !== '') {
                    ruleString += `  ${camelToKebab(key)}: ${value};\n`;
                }
            }
            ruleString += `}\n\n`;

            cssString += ruleString;
        }

        if (node.children && node.children.length > 0) {
            node.children.forEach(traverse);
        }
    };

    nodes.forEach(traverse);
    return cssString;
};

/**
 * Converts the JSON AST tree into a standard HTML string.
 * It applies the unique class names generated by `jsonToCss`.
 */
export const jsonToHtml = (nodes) => {
    let htmlString = '';

    const traverse = (node) => {
        const { type, id, settings, children } = node;
        const className = `cf-el-${id}`;

        let innerHtml = '';
        if (children && children.length > 0) {
            innerHtml = children.map(traverse).join('\n');
        }

        switch (type) {
            case 'Root':
                return `<div class="${className} cf-builder-root" id="${id}">\n${innerHtml}\n</div>`;
            case 'Row':
            case 'Column':
                return `<div class="${className}" id="${id}">\n${innerHtml}\n</div>`;
            case 'Heading':
                const Tag = settings.tag || 'h2';
                return `<${Tag} class="${className}" id="${id}">${settings.text || ''}</${Tag}>`;
            case 'Paragraph':
                return `<p class="${className}" id="${id}">${settings.text || ''}</p>`;
            case 'Button':
                return `<a href="${settings.url || '#'}" class="${className}" id="${id}">${settings.text || ''}</a>`;
            case 'Image':
                return `<img src="${settings.src || ''}" alt="${settings.alt || ''}" class="${className}" id="${id}" />`;
            case 'Spacer':
            case 'Divider':
                return `<div class="${className}" id="${id}"></div>`;
            default:
                return `<!-- Unknown element type: ${type} -->`;
        }
    };

    htmlString = nodes.map(traverse).join('\n');
    return htmlString;
};

/**
 * Combines the HTML, CSS, and Shopify Section wrapper schema into a final Liquid file.
 */
export const compileToLiquid = (ast, pageName = 'Custom Page') => {
    const css = jsonToCss(ast);
    const html = jsonToHtml(ast);

    // For a Shopify Section, we need to wrap the CSS in a <style> block
    // and provide a basic {% schema %} so Shopify recognizes it.

    return `
{% comment %}
    Auto-generated by ConvertFlow AI Page Builder
    Page: ${pageName}
    Date: ${new Date().toISOString()}
{% endcomment %}

<style>
/* --- Scoped Builder CSS --- */
${css}
/* --- End Scoped CSS --- */
</style>

<div class="cf-custom-page-wrapper">
    ${html}
</div>

{% schema %}
{
  "name": "${pageName} (CF Builder)",
  "settings": [],
  "presets": [
    {
      "name": "${pageName} (CF Builder)",
      "category": "Custom Pages"
    }
  ]
}
{% endschema %}
`;
};
